### ISSUE TITLE
Sending big files

### ISSUE THREAD

**Issue by RobinLinus** [RobinLinus/snapdrop#1]
"When sending big file from chrome on Android to chrome on windows, chrome of Android crash.
And when send big file from Windows chrome to Android chrome, snapdrop don't download file."

**Comment by msurguy** [comment]
@RobinLinus Along the same lines, what is the file size limit for this type of transfer?

**Comment by RobinLinus** [comment]
@msurguy I did not set any artificial file size limit. Though Chrome crashes if you send too large files. I am working on chunking the files during transfer to solve that problem.

**Comment by ericelliott** [comment]
I was just going to open a ticket about sending images and videos from my Samsung Galaxy S7 to Chrome on MacOS. Not working. Sadly, this is the primary use-case for me.
