### ISSUE TITLE
Please write instructions on how to quickly get started

### ISSUE THREAD

**Issue by yurivict** [RobinLinus/snapdrop#10]
There is index.js, but it expects /public folder which isn't in the project.

README doesn't say anything on how to run.

I suggest you make index.js run out of the box. If another projects are required, there is the way to link them up as submodules.

**Comment by frdmn** [comment]
:+1: 

The project is trending right now, so I assume a lot of new people will have the same issue.

**Comment by capira12** [comment]
I am sorry guys! I am very busy keeping the server up and well, I have job :D

**Comment by frdmn** [comment]
@capira12 No worries. We do understand that of course.

@all: Here's a temporary "getting started" guide:

1. `git clone` this repository
2. Run `npm install` to install all NodeJS dependencies
3. Run `bower install` to download all web libraries
4. Adjust the static folder to "/app" in the `index.js` file:

```diff
-- app.use(express.static(__dirname + '/public'));
++ app.use(express.static(__dirname + '/app'));
```

5. Run `npm start` to serve via Gulp

**Comment by yurivict** [comment]
It runs. Now it is supposed to share files between browsers that all open it on port 5000?

I opened port 5000 on both host and Android, but nothing happens. On Android it only shows blue circles.

**Comment by frdmn** [comment]
@yurivict Make sure to start the WebSocket server. Open a second shell and run:

    node index.js

**Comment by yurivict** [comment]
'node index.js' gets connections.

But browser sometimes doesn't show where to send, and sometimes it does list clients to send to, curiously including itself. When I select a file to send, it never shows any message on the target. And Android browser never shows anything but blue circles.

**Comment by fggfhghg** [comment]
@yurivict Run "gulp serve:dist" instead of "gulp serve"

**Comment by fggfhghg** [comment]
@yurivict Run "gulp serve:dist" instead of "gulp serve"

**Comment by fggfhghg** [comment]
@yurivict Run "gulp serve:dist" instead of "gulp serve"

**Comment by tristan-k** [comment]
I'm also struggling with the port [configuration](https://github.com/capira12/snapdrop/issues/20).

**Comment by yurivict** [comment]
The best thing the author of any package can do is to write instructions on how to use it as easy as possible.

Because software can be super high-tech and cool, but if nobody else can install it, nobody but the author can see that remarkable high-techness and coolness.
