### ISSUE TITLE
Add Generic Paypal Link

### ISSUE THREAD

**Issue by hunterjackson** [RobinLinus/snapdrop#100]
Hey I really like your product and I wanted to donate however the PayPal link you've given sends me to the German language PayPal making it a bit hard for me and I imagine other to navigate. I'm pretty sure PayPal has more generic links.

**Comment by RobinLinus** [comment]
Thanks a lot for the hint! 
I used the Paypal button wizard to create a new button. 
https://github.com/RobinLinus/snapdrop#support-the-snapdrop-community
Hope that solved the problem?

**Comment by hunterjackson** [comment]
Works great thanks!

**Comment by RobinLinus** [comment]
Thanks a lot!
