### ISSUE TITLE
How to auto-accept Download ALL files in current queue?

### ISSUE THREAD

**Issue by pstein** [RobinLinus/snapdrop#104]
Assume I select multiple (e.g. 50) files for transfer.
After each file I am prompted on the destination computer/smartphone if I really want to transfer/download it.

Having to click the "Download" button for each file is tedious and unnecessary.

How can click ONE time "Download" for accepting the reception of ALL files in current queue?

If this is currently not possible: Can this be implemented?

Peter

**Comment by PaulSzymanski** [comment]
Duplicate: https://github.com/RobinLinus/snapdrop/issues/82
