### ISSUE TITLE
How to assign an unique name to own device?

### ISSUE THREAD

**Issue by pstein** [RobinLinus/snapdrop#106]
When I open Snapdrop in the browser of my SmartPhone then occasional multiple (u to 3) other devices appear:

My tablet and my girl friends SmartPhone

All of them are displayed with the name "Android Firefox".

How can I distinguish between them (without trial and error)?

The best would be I could assign a unique name like "PetersSP".
How can I achieve this?

Peter

**Comment by 2br-2b** [comment]
Same as #69

**Comment by PaulSzymanski** [comment]
Resolved by https://github.com/RobinLinus/snapdrop/pull/91
