### ISSUE TITLE
Feature Request: Send text instead of files

### ISSUE THREAD

**Issue by russellweed** [RobinLinus/snapdrop#11]
In addition to sending binaries, it would be great if you could send arbitrary text to another device, such as simple text box to type or paste into.

**Who will use the feature?**
Anyone wishing to send text from their browser to their device (or vice versa)

**When will they use the feature?**
- Sending a long URL between an iPad and a Windows desktop (no iCloud tab sharing)
- Pasting large amounts of text (notes) between devices

**What is the user’s goal?**
There is a great app on iOS called "Clips" which uses iCloud to sync text snippets between your iDevices. Because it is 100% iCloud based, however, there's no way to send data to a Windows PC. Snapdrop could fill the hole here by providing said functionality.

**Comment by capira12** [comment]
What do you think about this implementation?

**Comment by russellweed** [comment]
This is a fantastic start, however there are a few further ways the implementation could be improved:

# General Problems
* Modal window says "Send Text" for a window title AND "Enter text" for a prompt, which is redundant; Additionally, the phrase "enter text" doesn't appear until one has already entered text, making it completely unneeded.
* When receiving long text (see below), the window does not scroll, making it impossible to view the entire contents.
* The phrase "tap" doesn't apply to non-touchscreen desktops; "click" would be more appropriate
* When sending a second Text message, the first text is still in the Edit window; you need to manually clear it out
* You can send a blank message, which still makes the other device play the "pop" sound when empty string is received, though it does not display the received window

# On Desktop
* "Send Text" window is very small; wastes screen space
* "Copy" button in Received Text window doesn't work on Firefox; didn't test other browsers. May be a security thing?

# On Mobile
* Text entry dialog jumps around the screen when editing long text
* Its hard to scroll the text entry dialog on iOS

# Sample Text Used

Bacon ipsum dolor amet turkey rump swine, strip steak chuck tenderloin cupim shank pork loin pastrami pig meatloaf tail. Ribeye chicken meatball swine boudin. Jowl turducken hamburger andouille. Tri-tip frankfurter pork belly sirloin turkey kielbasa corned beef shank bacon chuck andouille. Corned beef kielbasa t-bone, beef boudin porchetta short loin kevin pork belly fatback chicken prosciutto strip steak flank cupim. Cow pancetta shoulder, venison doner kevin bacon hamburger jowl turkey chuck ham hock picanha ground round short loin.

Ham sausage filet mignon hamburger shoulder, cow meatball t-bone fatback. Prosciutto corned beef jowl hamburger, meatball frankfurter fatback ham hock pancetta tenderloin turducken ribeye doner venison swine. Bresaola landjaeger turkey prosciutto frankfurter chuck filet mignon short ribs corned beef leberkas. Hamburger ball tip pork loin flank strip steak rump. Capicola kielbasa strip steak ground round turducken flank tongue. Pancetta jowl capicola shankle tenderloin leberkas sirloin pork ham hock ham landjaeger. Tenderloin capicola flank, t-bone frankfurter pork chop prosciutto ham shoulder kevin.

(http://baconipsum.com/)

**Comment by jrruethe** [comment]
This feature is a life saver. I do agree that the text box needs to be larger.
