### ISSUE TITLE
[Feature Request] Context menu integration on windows

### ISSUE THREAD

**Issue by jazir5** [RobinLinus/snapdrop#114]
I want to be able to right click anything in explorer and be able to immediately share it to snapdrop from the context menu. Is this doable?

**Comment by PaulSzymanski** [comment]
Unfortunately, this is not possible with web apps.

**Comment by schlagmichdoch** [comment]
Apparantly, on Windows this is possible with an experimental flag in edge. It uses the attribute `share_target` in the manifest.json as described in [this issue](#525).

Here is a tutorial and there is also a demo which works pretty well 🚀 
https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-files

I plan to implement this, so feel free to reopen this issue @PaulSzymanski :)

**Comment by schlagmichdoch** [comment]
This is now implemented alongside many other improvements on:
https://pairdrop.net/

How-To:
https://github.com/schlagmichdoch/PairDrop/blob/master/docs/how-to.md#how-to
