### ISSUE TITLE
Permission denied with docker

### ISSUE THREAD

**Issue by gitalm** [RobinLinus/snapdrop#116]
Thanks for this great software. 
I downloaded the package (git clone git@github.com:RobinLinus/snapdrop.git failed) and unpacked it and renamed it to snapdrop.
Then i installed docker-compose and executed 

> sudo docker-compose up 

in the directory. Without _sudo_ there was a error

>ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running? If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

Everything started, but i cannot display the webpage: 403 Forbidden (nginx/1.17.9)
and in the bash

> nginx_1  | 2020/03/10 14:06:19 [error] 6#6: *1 "/usr/share/nginx/html/index.html" is forbidden (13: Permission denied), client: 172.18.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1  | 172.18.0.1 - - [10/Mar/2020:14:06:19 +0000] "GET / HTTP/1.1" 403 153 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:73.0) Gecko/20100101 Firefox/73.0"

**Comment by PaulSzymanski** [comment]
> Without sudo there was a error

How to manage docker without superuser privileges: https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

> Everything started, but i cannot display the webpage: 403 Forbidden

After running `sudo chmod -R 755 .` within your snapdrop directory you shouldn't get the error anymore.
If you still do get the error you might have some access control list or mandatory access control enabled. In that case please run `ls -laZ` within the client directory and tell what you get.

**Comment by gitalm** [comment]
Dear Paul,

thanks for the help. But now the devices can't see each other. I logged to Smartphones to the same adress, but both say _Open snapdrop on other devices to send files_ (Unfortunately the Smartphones a the same brand)

> nginx_1  | 192.168.178.85 - - [11/Mar/2020:07:44:19 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Linux; Android 9; SM-G900F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Mobile Safari/537.36" "-"
nginx_1  | 192.168.178.85 - - [11/Mar/2020:07:44:19 +0000] "GET /server/webrtc HTTP/1.1" 101 165 "-" "Mozilla/5.0 (Linux; Android 9; SM-G900F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Mobile Safari/537.36" "-"


Thanks

**Comment by PaulSzymanski** [comment]
This seems to be similar to #111.
