### ISSUE TITLE
Unable to transfer files

### ISSUE THREAD

**Issue by Mhowser** [RobinLinus/snapdrop#117]
When I try to send a small picture to my android phone, it gets stuck saying it is transferring. When I open the dev console I can see the error.

I am using [Brave browser](https://brave.com) for desktop and mobile, same thing happens in Firefox.

![image](https://user-images.githubusercontent.com/24195572/77244382-7e541d00-6bd1-11ea-8c74-3debf9b4965d.png)
![image](https://user-images.githubusercontent.com/24195572/77244426-e4d93b00-6bd1-11ea-830c-72efd8c52c6e.png)

**Comment by RobinLinus** [comment]
Thanks for the hint. The server was down because of too much traffic. It's up again
