### ISSUE TITLE
E2E Encrypt files

### ISSUE THREAD

**Issue by 2br-2b** [RobinLinus/snapdrop#128]

**Comment by lrq3000** [comment]
Please clarify whether the data travels unencrypted on the servers, or if the server is only used to initiate the file transfer between the devices.

**Comment by RobinLinus** [comment]
Snapdrop uses only WebRTC peer-to-peer connections for file transfer. The server is used only for signaling (establishing p2p connections). AFAIK, WebRTC is even SSL encrypted. 

Long story short: The server certainly cannot access your files.

* The previous Snapdrop version had a WebSocket fallback for browsers that don't support WebRTC though in the current version this is not implemented.
