### ISSUE TITLE
Feature Request : iOS shortcut for share sheet, Share to Snapdrop

### ISSUE THREAD

**Issue by jaredzimmerman** [RobinLinus/snapdrop#129]
Since I use a chromebook and my family and I use iPhones and everyone else is on a macbook it can be difficult to easily share links to a chromebook, a share extension via shortcuts would make this much easier and faster

**Comment by 2br-2b** [comment]
In order to do this, we would need to create a Snapdrop iOS application. I would love to implement this, but it would be tough to add.

**Comment by jaredzimmerman** [comment]
yes, I understand, I assume a simple wrapper app would be all that you'd need?

**Comment by child-duckling** [comment]
#156 might help :)
