### ISSUE TITLE
Can't access in incognito (firefox)

### ISSUE THREAD

**Issue by ThracianKnight1907** [RobinLinus/snapdrop#130]
Title says it all. It used to work until today but now it throws a "500 Internal Server Error
nginx" error when accessing it on Private Mode in Firefox.

The website works fine when accessed from a regular (non private) windows

**Comment by ThracianKnight1907** [comment]
Whatever it was, it appears to be fixed now

**Comment by ThracianKnight1907** [comment]
Reopened because it's happening again. Seems like its intermittent

**Comment by PaulSzymanski** [comment]
Hi, this was probably due to server issues that should be resolved now. See #73. Please reopen if you are still seeing this.
