### ISSUE TITLE
Don't work on devices without WebRTC support

### ISSUE THREAD

**Issue by jleaves** [RobinLinus/snapdrop#131]
First I'd like to express my thanks for this great tool. It's simple yet elegant. I wish I've known this earlier.

Currently, it works fine on my PC and Apple devices on the latest iOS version. However, I can't get it to work on my old iPhone on iOS 10.3 which I use occasionally. It shows up in the device icon list, but I can't get it to send or receive anything. (Messages will simply not send, and files will stuck at "Transfering", no matter the iPhone is the sender or receiver.)

I know Safari on iOS 10 [doesn't support WebRTC protocol](https://caniuse.com/#feat=rtcpeerconnection), but it [does support WebSocket](https://caniuse.com/#feat=websockets), so it should work. Can anyone help me troubleshoot what is going wrong?

**Comment by PaulSzymanski** [comment]
Hi, the first version of Snapdrop had a fallback to WebSocket as it provided an important value for iPhone users. However, as WebRTC is supported since iOS 11 (September '17) and because transferring files over WebSocket induces high (costly) traffic over the Snapdrop server the fallback was removed.

**Comment by jleaves** [comment]
> Hi, the first version of Snapdrop had a fallback to WebSocket as it provided an important value for iPhone users. However, as WebRTC is supported since iOS 11 (September '17) and because transferring files over WebSocket induces high (costly) traffic over the Snapdrop server the fallback was removed.

Thanks for your reply, and sorry to reopen this issue. I see that WebSocket support is removed due to traffic and cost, and I understand that Snapdrop, as a free and open source application, has to streamline the code and operative cost to survive.

I am considering building one on my own server for personal use. Could you indicate which commit is the last one that supported WebSocket? I'd really appreciate that.

**Comment by jleaves** [comment]
> > Hi, the first version of Snapdrop had a fallback to WebSocket as it provided an important value for iPhone users. However, as WebRTC is supported since iOS 11 (September '17) and because transferring files over WebSocket induces high (costly) traffic over the Snapdrop server the fallback was removed.
> 
> Thanks for your reply, and sorry to reopen this issue. I see that WebSocket support is removed due to traffic and cost, and I understand that Snapdrop, as a free and open source application, has to streamline the code and operative cost to survive.
> 
> I am considering building one on my own server for personal use. Could you indicate which commit is the last one that supported WebSocket? I'd really appreciate that.

By the way, a small suggestion: maybe modify the README to state that WebSocket support is deprecated. @PaulSzymanski
