### ISSUE TITLE
how to distinguish my windows chrome and another windows chrome

### ISSUE THREAD

**Issue by e71828** [RobinLinus/snapdrop#134]
thanks very much.
every pcs' name in the web are the same, windows chrome.
how could I map a special name.

**Comment by wyudong** [comment]
In server/index.js, use `this.id` (a.k.a UUID) to differentiate devices in `_setName` method.

**Comment by e71828** [comment]
@wyudong thanks, but I use the public wesite, I have not deploythe server. 
 could I input some commands in the chrome console by F12

**Comment by wyudong** [comment]
Do you mean you are using snapdrop.net but want to display an unique id for each peer's icon by *hacking* the browser console? Maybe use `document.getElementsByTagName('x-peers')` to iterate the dom of peers and you will get the id of each `x-peer` easily and continue to do what you want.

**Comment by 2br-2b** [comment]
What if we assigned each computer a random name or ID when they connected to Snapdrop? That way, if two Windows Chromes connect, you can compare the names to determine which computer is the correct recipient.

We could also allow users to enter their own IDs, but then that could potentially lead to duplicates. This could be abused if a malicious actor were to assign their computer the same name as another recipient in an attempt to trick the users.
