### ISSUE TITLE
Android/iOS apps for SnapDrop

### ISSUE THREAD

**Issue by haritvsmurali** [RobinLinus/snapdrop#147]
Hi,

SnapDrop being great replacement for AirDrop, ShareIt, Xender etc., in Cross Platform file segment.

We want Android/iOS apps for SnapDrop.

Thanks!

**Comment by wyudong** [comment]
why not save a bookmark on your phone's desktop?

**Comment by PaulSzymanski** [comment]
Snapdrop is a Progressive Web App. You can install it to your devices by clicking the phone icon on the upper right corner. If the icon is not showing up the PWA should already be installed.
