### ISSUE TITLE
Doesn't work on Android 11 Beta

### ISSUE THREAD

**Issue by kineticscreen** [RobinLinus/snapdrop#150]
Snapdrop no longer works on the Android 11 Beta. Both sending or receiving files or messages are ignored in either direction.

**Comment by PaulSzymanski** [comment]
I can not reproduce this on Android 11 (API Level 30) run in an emulator. Can you please check if you still see this error? Please check the console output for errors.

**Comment by kineticscreen** [comment]
Service Worker registered
network.js:18 WS: server connected
network.js:27 WS: Object
network.js:27 WS: Object
network.js:27 WS: Object
manifest.json:1 Manifest: Method should be set to either GET or POST. It currently defaults to GET.
manifest.json:1 Manifest: Enctype should be set to either application/x-www-form-urlencoded or multipart/form-data. It currently defaults to application/x-www-form-urlencoded
content.js:1 {"type":"get_background_image","requestDate":"2020-08-08T06:29:58.269Z"}
network.js:27 WS: {type: "peer-joined", peer: {…}}
ui.js:111 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
_bindListeners @ ui.js:111
PeerUI @ ui.js:90
_onPeerJoined @ ui.js:25
(anonymous) @ ui.js:16
fire @ network.js:502
_onMessage @ network.js:33
ws.onmessage @ network.js:19
network.js:27 WS: {sdp: {…}, type: "signal", sender: "87199c5e-1479-4e9e-9837-d48fa94c5791"}
network.js:429 [Violation] 'load' handler took 309ms
network.js:27 WS: {type: "ping"}
network.js:429 [Violation] 'load' handler took 181ms
network.js:429 [Violation] 'load' handler took 339ms
network.js:429 [Violation] 'load' handler took 317ms

**Comment by kineticscreen** [comment]
This seems to be resolved - possibly with the final release of Android 11?
