### ISSUE TITLE
I have created a Flutter app for Snapdrop 

### ISSUE THREAD

**Issue by congnguyendinh0** [RobinLinus/snapdrop#156]
I have created a Flutter app for Snapdrop 

https://github.com/congnguyendinh0/snapdrop_flutter

**Comment by mubashir-rehman** [comment]
Looking forward to it. Amazing.

**Comment by child-duckling** [comment]
Added to #166

**Comment by RobinLinus** [comment]
Thanks! 
Resolved 6044103bfc2287ed54dff6a0d40dbe7bf72eeb44

**Comment by RobinLinus** [comment]
Thanks! 
Resolved 6044103bfc2287ed54dff6a0d40dbe7bf72eeb44
