### ISSUE TITLE
Renaming the IMG file name as it is while transferring from IOS to Windows 10

### ISSUE THREAD

**Issue by adarsh-mamgain** [RobinLinus/snapdrop#160]
## I love this web application 😄 😍 it is super easy to use. Just a concern which might help your future users + myself.

While transferring **_IMG files_** from my iPhone the names changes and gets saved as a random string name. 
The **_video file_** transfers correctly with same file name.

It is creating the problem for sorting and organising my IMG files.

Please fix this 😃 ASAP as the app is great. @RobinLinus

**Comment by RobinLinus** [comment]
Unfortunately, iOS Safari doesn't allow to name downloaded files. So, we've to wait until Safari fixes the issue...
