### ISSUE TITLE
Website Monetization with BAT

### ISSUE THREAD

**Issue by Mhowser** [RobinLinus/snapdrop#163]
Hi @RobinLinus, 

I just wanted to introduce a new method of potential monetization for the SnapDrop website with [BAT](https://basicattentiontoken.org) (Basic Attention Token).
This token is used by [Brave Browser](https://brave.com/). A fast, privacy-oriented, open-source browser with a goal to "improve the efficiency of digital advertising by creating a new token that can be exchanged between publishers, advertisers, and users."

Users of Brave can collect BAT by viewing discreet ads and tip their favorite content creators and websites (either one time or a recurring monthly tip). Content creators and website owners can collect these tips by verifying with Uphold (users who wish to send tips do not need to verify).

[As of right now there are over **850,000** publishers!](https://batgrowth.com/)

You can sign up at https://creators.brave.com/

**Comment by kubark42** [comment]
Why does this look like spam which should be closed and the user reported?

**Comment by Mhowser** [comment]
Why don't you look at my account and stop jumping to conclusions?

**Comment by kubark42** [comment]
1. Because you opened up an issue when it's not. This increases signal to noise ratio.
2. Because it's not our job to investigate every random poster on the internet. We each have our own lives to live.
3. Because when was the last time any of us got an unsolicited requests for monetization and it *isn't* spam?
4. Because everything about your post screams spam. 850,000 publishers! Here's the convenient sign up link! Money!

**Comment by Mhowser** [comment]
The issues tab isnt explictly for just issues ya know. I could have put this in pull requests, but I'm not an idiot.

I use Brave all the time and I like what they are trying to accomplish. I also like this project very much, and I thought the maintainer  would like to know about a new way to support the snapdrop server. If you think thats spam then you should stay off this site and go to coolmathgames.

By the way it does not take that long to see I'm clearly not a spam account.

**Comment by Mhowser** [comment]
Would you look at that!
![IMG_20200902_051302](https://user-images.githubusercontent.com/24195572/91979789-23c00080-ecdb-11ea-9d0b-6cf192883e8e.jpg)

Even Wikipedia is a verified publisher. Still think its spam?

**Comment by RobinLinus** [comment]
I've heard lots of scammy stuff about BAT. 
However, thanks for caring about Snapdrop!
