### ISSUE TITLE
Page crashes on Safari 14 when a peer connects

### ISSUE THREAD

**Issue by Lethalmathematix** [RobinLinus/snapdrop#169]
If you load the page with 0 peers, no problemo.

As soon as a peer connects, or you join a room with existing peers, the page reloads a couple of times and the shows the browser error page saying "A problem repeatedly occurred with https://snapdrop.net"

Seems to be a problem with a non-empty "peers" webrtc message.

It's just specific to Safari 14.

Works fine on Chrome, Edge, Firefox, and Safari 13.1.

**Comment by kINGPINcsgo** [comment]
Having the same troubles. Not working on iOS 14.

**Comment by Lethalmathematix** [comment]
Issue was because of a faulty Safari update.

The latest update fixes it.
