### ISSUE TITLE
Apk file send thorough snapdrop, does not work on mobile

### ISSUE THREAD

**Issue by wangki** [RobinLinus/snapdrop#17]
I used android 5.0.1, I send Apk( android app package ) through snapdrop, and it doesn't work

I do not know what cause that issue. 

(it works fine when i downloaded it on mobile)

**Comment by bithakr** [comment]
I replicated the issue using Android 6.0.1 w/ S TouchWiz ROM on a Galaxy On5 today. No errors or anything. When I sent a text the page bkgrnd darkened but it did not show. Chrome on PC and Chrome Dev on Android, both updated.
