### ISSUE TITLE
Add Android App to readme

### ISSUE THREAD

**Issue by fm-sys** [RobinLinus/snapdrop#172]
I created an Android App for Snapdrop.

See https://github.com/fm-sys/snapdrop-android. Of course, you can also use the browser/PWA, but this app allows you to **also send files directly from other apps via the share action**. All website functions should be also supported inside the app... 
If you find bugs, feel free so create an issue in my repo.

Would it be ok to list my app in the readme? Of course, I saw #153 but the main advantage of this app is that it is much better integrated into the OS than a PWA...

![Screenshot_2020-10-06-12-41-29_framed (Phone)](https://user-images.githubusercontent.com/64581222/95191809-8ff9bc80-07d1-11eb-8e93-98a44d770ebb.png)

**Comment by bdcarr** [comment]
Oh this is great - I came here because my VPN was preventing discovery, and since it's not a native app, I wasn't able to add it to nordvpn's Split Tunnelling config. Now I can just use the app! Thanks mate.

**Comment by RobinLinus** [comment]
Thanks for the hint! 
Done in 4988e9fe7ec47e1f0a349c9eff60b662c40146d4
