### ISSUE TITLE
Messages not working on desktop

### ISSUE THREAD

**Issue by YKA1github** [RobinLinus/snapdrop#174]
I long-tap for message on my MacBook Air 2020, and it doesn't work. It just does the file transfer. On my iPad 6th Gen., it works perfectly. Can you guys fix this? It is probability a detection fault in the code

Thanks
YKA1

**Comment by najtin** [comment]
Could you provide more detail about the issue? 
What do you mean by long-tap, and what do you mean by message?
What is the expected behavior? What are you observing instead?

**Comment by YKA1github** [comment]
Hello @najtin, 
In SnapDrop, it says long-tap to message
Message as in you can say "Hello" to someone and someone can say "Hello" and talk
I expected what happened to my iPad which was that it asked what is the message you want to send and I typed a message and it was sent to my Mac. I was observing if my Mac can also message, which it couldn't.

**Comment by YKA1github** [comment]
Maybe @RobinLinus needs to check on this issue

**Comment by YKA1github** [comment]
> Could you provide more detail about the issue?
> What do you mean by long-tap, and what do you mean by message?
> What is the expected behavior? What are you observing instead?


Hello @najtin, 
In SnapDrop, it says long-tap to message
Message as in you can say "Hello" to someone and someone can say "Hello" and talk
I expected what happened to my iPad which was that it asked what is the message you want to send and I typed a message and it was sent to my Mac. I was observing if my Mac can also message, which it couldn't.

**Comment by najtin** [comment]
Ah, wow, i was totally oblivious to this feature of snap drop! :D 
Never noticed it. Sorry

**Comment by YKA1github** [comment]
> Ah, wow, i was totally oblivious to this feature of snapdrop! :D
> Never noticed it. Sorry

@najtin so can you fix it or would @RobinLinus or someone else have to fix it. This has something to do with the actual code

**Comment by puf17640** [comment]
Where does it say 'long tap to message'
![image](https://user-images.githubusercontent.com/17516174/96577712-50a09500-12d4-11eb-851b-891b392508fe.png)

**Comment by najtin** [comment]
On some touch devices "right click to send a message" is "long tap to send a message"
![Screenshot_20201020-131222](https://user-images.githubusercontent.com/42641080/96578877-37004d00-12d6-11eb-9a61-ce32a6702d98.png)

**Comment by puf17640** [comment]
Okay I see, I will look into this in a few hours, might take some time as I haven't worked with the codebase yet but this shouldn't be an impossible fix 👍

**Comment by puf17640** [comment]
Okay so I just read the whole thread again before starting to check the code and I have 1 question, why does he need to long press on his macbook air 2020 while i have to right click on my macbook pro 2019? does it have a touchscreen?

**Comment by najtin** [comment]
@YKA1github can you double check that it says "long tap" on your MacBook?

**Comment by puf17640** [comment]
@YKA1github ?

**Comment by najtin** [comment]
seems to be a non issue now

**Comment by rochakagrawal** [comment]
This is indeed an issue. I am trying to send a message from chromebook but right click does not work. From ios - i can long touch to send a message, but unable to do that form chromebook where right click just opens the standard chrome menu

please fix

**Comment by YKA1github** [comment]
Hey Guys I am incredibly sorry I couldn't keep in touch. New school so- It's a lot to take care of with COVID too. It is not an issue. How this all works is that with mobile devices it is long tap, and with computers it is right-click. I hope you all have a great new year.

Thanks
YKA1
