### ISSUE TITLE
iOS "open as" doesn't always work

### ISSUE THREAD

**Issue by swotai** [RobinLinus/snapdrop#19]
Some files can be opened in iOS Safari browser, which will present with further options to open in other apps.  For example, epub and pdf URLs in Safari will lead to an interface which allows the file to be opened in iBooks.
When sending these files to iOS from anywhere (pc or mac or another ios device), the snapdrop site presents the option to "download".  This opens a new tab.  But this new tab is now blank.

**Comment by RobinLinus** [comment]
Yes, but that's due to file type limitations on iOS. 
Maybe there are hacks for certain file types, but in general you're limited to media files.
You are welcome to make suggestions...
