### ISSUE TITLE
Visibility prompt

### ISSUE THREAD

**Issue by Shua131** [RobinLinus/snapdrop#191]
![SmartSelect_20201123-164715_Samsung Internet](https://user-images.githubusercontent.com/67172091/100028175-922cd000-2dab-11eb-8c56-86a2529a8dc6.jpg)
This prompt looks like you should be able to change who you are visible to, but I cannot change anything. Is there a way to change this?

**Comment by fm-sys** [comment]
AFAIK this is only an information, nothing users should be able to change. But what would other options be? Cause there are no snapdrop accounts or something like this, there are no other visibility options which would make sense...

**Comment by Shua131** [comment]
I would simply suggest making it say something like "This website allows you to be discovered by everyone on this network." As the "Allow me" prompt seems to indicate the ability to change

**Comment by Shua131** [comment]
I did not mean to close this, I accidentally misclicked, apologies.

**Comment by Shua131** [comment]
H

**Comment by Shua131** [comment]
Apologies if I was a bother, I was just a bit confused and wanted to give some helpful suggestions. Thank you for helping me.

**Comment by abhijit-hota** [comment]
I also suggest changing the text color to something else (grey with proper contrast, maybe). My eyes see **blue**, my brain thinks **link**.

**Comment by zhuhangan** [comment]
> AFAIK this is only an information, nothing users should be able to change. But what would other options be? Cause there are no snapdrop accounts or something like this, there are no other visibility options which would make sense...

The connection can be followed by a random parameter, such as: https://snapdrop.net/?rd=343cva . users accessing the same link are visible. In this way, if I want to send a file to someone, I can give him a link that I customize.

**Comment by RobinLinus** [comment]
Should be fixed with ea9ce951123b2cc7ac8b577588e24fe7d9f79918
