### ISSUE TITLE
Sharing link from Android phone to laptop is awkward

### ISSUE THREAD

**Issue by elias6** [RobinLinus/snapdrop#193]
Overall, I like Snapdrop, but it does something annoying.

Sometimes I will be on a page in Chrome on my phone (a Pixel 2 running Android 11), and I will want to read it on my laptop (a Mac running macOS 10.15.7 and Chrome 86). I will go to https://snapdrop.net/ on my laptop. Then on my phone, I will click Chrome's menu, then "Share...", then "More", then "Snapdrop". I will long-press on the icon for my laptop, and a dialog will show that is pre-populated with what looks like the URL. I will hit send, and a dialog will show in Snapdrop on my laptop. But instead of showing a clickable URL, it will show something like this:

![Snapdrop message received dialog](https://user-images.githubusercontent.com/510781/100136628-2183c300-2e40-11eb-9f00-b339b25d3de2.png)

Clicking the URL does not open the link. If I try to click and drag to select only the URL, hoping to be able to open it using Chrome's context menu, it selects the whole message. I know I can copy and paste the whole message somewhere and delete the title, but that is awkward (and less tech-savvy people may not be able to figure it out at all).

Can this be fixed? I am not too familiar with how Snapdrop works, but this seems fixable. If I send a message containing only the URL (maybe by editing the message before sending it, or by copying and pasting the URL from the address bar into a new message), it is clickable on my laptop.

**Comment by Bellisario** [comment]
The problem is that Snapdrop shows URLs only if you share it without other text... so, this is NOT a bug, this is a preference of the app. I know that some users like you, would like this, but I think that if you need to share URLs, why with other text? And, also, some other users can be annoyed if they would like share text plain and not text with style or URLs...

**Comment by elias6** [comment]
"I think that if you need to share URLs, why with other text?" Because that is what Snapdrop does on its own when I send links through it using the "Share" menu on my phone.

I think that ideally, there should be a (simple and easy) way to share just the URL, or URLs should be clickable even if they are sent along with other text. Or if neither of those are viable options, I should be able to select part of the message, to open the URL using Chrome's context menu or to copy and paste it somewhere.

**Comment by radiohazard-dev** [comment]
Having just tested this out, I think this is simply Android/Chrome sharing functionality: when you click the share button in the web browser and send it to some app, some parameter gets filled with the text you see in that message, which includes the title of the webpage by default. Prior to sending the message, you can edit it and remove that title, and it works fine from there.

Mobile:
![Screenshot_20201208-182709_Chrome](https://user-images.githubusercontent.com/37482938/101557731-33f31600-3983-11eb-9063-1c519eb68ff1.png)
Desktop:
![msedge_mLT9vKqf8U](https://user-images.githubusercontent.com/37482938/101557777-48371300-3983-11eb-90ca-9fd5392c6285.png)

**Comment by elias6** [comment]
@radiohazard-dev you are confirming what I said.

I know I can remove the text at the beginning of the message. For me, it is only an inconvenience in an otherwise great service. But someone less familiar with Snapdrop may not even notice that text (since the input on the dialog is tiny, and only shows the end of the message). Someone less tech-savvy or more mobility-impaired than me may have trouble scrolling back to the beginning of the URL, positioning the cursor there, and deleting everything before it.

About this being "simply Android/Chrome sharing functionality", why doesn't this happen if I share a link on WhatsApp, Signal, or Slack?

**Comment by radiohazard-dev** [comment]
I did some reading, and this does seem to be Snapdrop's fault after all, or at least partly. Progressive Web Apps can register themselves as share intent targets on Android through manifest.json, which passes some parameters to the app via GET or POST.

Now, I haven't yet looked at how the code handles these parameters (or which Android parameters map to the GET,) so I don't know whether Snapdrop is simply stuck with getting the whole IntentSubject+IntentText shebang, or an adjustment here or there can fix that.

**Comment by radiohazard-dev** [comment]
Found it!
`WebShareTargetUI` in `client/scripts/ui.js` defines the behavior for handling these parameters from `manifest.json`.
https://github.com/RobinLinus/snapdrop/blob/9db8c4ce8cef15ea41319846483ee526874306b3/client/scripts/ui.js#L467-L482
I imagine `title` (or `text`) is what is being ignored by most apps, and Chrome sets this to be the title of the website you're sharing.

**Comment by abhijit-hota** [comment]
What about a regex match for urls to make them clickable?

**Comment by radiohazard-dev** [comment]
That'd be great, and a lot easier for the user.

**Comment by RobinLinus** [comment]
Here's a quick fix f3e3f83f3f53a7d75eb7d95b46c9e91a9fbac79f
