### ISSUE TITLE
Sendings Android Apps?

### ISSUE THREAD

**Issue by Krrishdhaneja** [RobinLinus/snapdrop#197]
Is there any way to send android apps using Snapdrop? Cuz I didn’t find any way of doing that and i can send android apps using ShareMe and ShareIt etc. Is there any way of doing a thing like that?

**Comment by abhijit-hota** [comment]
You can share the `.apk` file but not the installed apps (like you do in ShareIt).

**Comment by Krrishdhaneja** [comment]
That think i know, but isn’t there any way of implementing it?

**Comment by fm-sys** [comment]
Snapdrop is a website and therefore can't extract installed apps. (Would be bad if website can 😅). 
But you can search for "apk extractor" on Google Play to get the apk of an installed app and share this apk file via Snapdrop

**Comment by timleg002** [comment]
I don't know if there's an app for SnapDrop, but it could be implemented natively in the app. I don't recall there being a way for Chrome to read from the app folder.

**Comment by Krrishdhaneja** [comment]
If this website is written in JS why don’t we write it in react native. Isn’t this sounds good?

**Comment by abhijit-hota** [comment]
I don't think Snapdrop needs to/shall/will incorporate this feature. Snapdrop signs in simplicity and cross-platform support so this seems irrelevant.

**Comment by Krrishdhaneja** [comment]
We can use react native on iPhone as well as Android, so it would be nice enough.

**Comment by fm-sys** [comment]
> 
> 
> We can use react native on iPhone as well as Android, so it would be nice enough.

There is an [android app](https://github.com/fm-sys/snapdrop-android) which I created myself (IMHO absolutely recommendable ;-)), as well as a [flutter app](https://github.com/congnguyendinh0/snapdrop_flutter) which can be installed AFAIK on iPhone as well as on Android... 

So I don't see a real need for another third party app, but if someone wants to do it as a beginner project for learning React Native - why not?

**Comment by Krrishdhaneja** [comment]
Good idea ...

**Comment by Krrishdhaneja** [comment]
But is there any feature in react native to access the apk of an app?

**Comment by Krrishdhaneja** [comment]
And in the flutter version of this i found only the apk and not the ipa(that is what i think the extension for iphone app is. Please correct me if i am wrong.)

**Comment by timleg002** [comment]
> But is there any feature in react native to access the apk of an app?

I doubt there is one. You can code one, it would be just accessing some files, however, I doubt extracting an app is going to be hard. However, I'd be more confident in doing so via Kotlin, I may be wrong though.

**Comment by timleg002** [comment]
I read up on this matter, and I found this answer:
https://stackoverflow.com/questions/11012976/how-do-i-get-the-apk-of-an-installed-app-without-root-access

Someone needs to make an app folder parser with visible results, thus showing a pic of it and its name (+package name, preferably), then upon clicking on it, get the package name of it, and grab the apk from the apk folder. 

Some of this needs to be done via shell, however, I don't know if there is a way to get shell access via React Native.

**Comment by Krrishdhaneja** [comment]
Alright, sounds great(idea of kotlin) but how would the apps like apk extractor perform this action?

**Comment by timleg002** [comment]
> Alright, sounds great(idea of kotlin) but how would the apps like apk extractor perform this action?

They most likely perform it just like it's said in the answer (both mine and the StackOverflow one I included)

**Comment by Krrishdhaneja** [comment]
Ok

**Comment by Krrishdhaneja** [comment]
Now should i close this or @RobinLinus would work on this ?

**Comment by timleg002** [comment]
I opened an issue on their GitHub app repo, probably you should close this.

https://github.com/fm-sys/snapdrop-android/issues/25
