### ISSUE TITLE
WebRTC connection doesn't work between Chrome and 'Android Browser'

### ISSUE THREAD

**Issue by RobinLinus** [RobinLinus/snapdrop#2]
Also in Android browser the dialog is unreadable blurry.

**Comment by armandojrod** [comment]
Can confirm Chrome beta for Windows and Chrome beta for Android doesnt work.

**Comment by nmaggioni** [comment]
This bug persists for me with Chrome (Android) v69 & Chromium (Linux) v69, the transfer never begins since no confirmation dialog appears on the receiving end.

Chrome (Android) v69 & Firefox (Linux) v62 works flawlessly, though.
