### ISSUE TITLE
"Download all" feature while receiving multiple files

### ISSUE THREAD

**Issue by JFMugen** [RobinLinus/snapdrop#201]
I send 31 files from PC to Android Phone (5.1) and i had to click download 31 times, which was annoying imo. Is it possible to add a "download all" or "trust this site" button or something like that?

**Comment by titivermeesch** [comment]
@RobinLinus Could I work on this?

**Comment by RobinLinus** [comment]
@titivermeesch how would you solve that? I guess that requires zipping the files? https://stackoverflow.com/questions/18451856/how-can-i-let-a-user-download-multiple-files-when-a-button-is-clicked

Much nicer is to use [File System Access](https://wicg.github.io/file-system-access/) API. However it's only available on [Chrome-like browsers](https://caniuse.com/native-filesystem-api).

**Comment by abhijit-hota** [comment]
> Looks like Chrome's default setting is that you still have to manually save every file, though.

😕

Zipping is a potential solution as you told. That's what Google Drive does when you download multiple files. 

I don't really like going into the downloads folder and unzipping them but it seems to be the most compatible way.

**Comment by JFMugen** [comment]
@RobinLinus Just letting you know, workaround demo site downloaded 3 files without asking on phone. (that was what i wanted while creating the post) 

On pc, it downloaded one and asked if it is ok to download multiple files as a pop-up, which is ok too.

(by the way, I am using Kiwi Browser, it is a Chromium browser)

**Comment by titivermeesch** [comment]
What about having the possibility? You would have 2 buttons, one to download as a zip.

About the File System Access API, it seems like only IE is not supported, so maybe the solution is to use the FSA API and have a fallback implemented like it is in the demo in case it's not available? Compatibility can be found [here](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem).

The only issue with this is that it's still experimental.

**Comment by abhijit-hota** [comment]
> On pc, it downloaded one and asked if it is ok to download multiple files as a pop-up, which is ok too.

This should be the ideal case according to me.

**Comment by titivermeesch** [comment]
@abhijit-hota So maybe just like in the demo then? It would work for everyone, even older browsers

**Comment by abhijit-hota** [comment]
> @abhijit-hota So maybe just like in the demo then? It would work for everyone, even older browsers

Yep, that's neat. But, does the demo **download multiple zip files** or **zips the jpg files and then downloads them**?

What happens if I download multiple images or pdf files?

**Comment by titivermeesch** [comment]
Very interesting. Every option seems to have back draws. The one in the demo looks likethe best for me though, except for the caveat. I know a Chrome extension can access the settings and maybe change them if the user wants it, but that does not seem possible for normal apps.

Do you know a way to access chrome settings maybe? Maybe even read access, not write access. If that's a possibility a fix could be to zip them if that setting is enabled. I'm not sure if it's enabled by default though. The setting is not enabled for me and I don't remember touching it.

For your point about zip files, it seems like the author just provided zipped images, so this does not require zip files to work.

**Comment by abhijit-hota** [comment]
> Do you know a way to access chrome settings maybe?

I am not aware of anything like that 😅. If we can access the settings and check whether the user has it enabled, then we can probably change our downloading method and notify them about it (Something like _You need to disable ...._ ).

> For your point about zip files, it seems like the author just provided zipped images, so this does not require zip files to work.

Oh, great then!

**Comment by RobinLinus** [comment]
> it seems like only IE is not supported

Unfortunately not. There is [File System API](https://caniuse.com/mdn-api_filesystem) and [File System Access API](https://caniuse.com/native-filesystem-api). The one we need is the latter which is supported only in Chrome-like browsers.

**Comment by titivermeesch** [comment]
> > it seems like only IE is not supported
> 
> Unfortunately not. There is [File System API](https://caniuse.com/mdn-api_filesystem) and [File System Access API](https://caniuse.com/native-filesystem-api). The one we need is the latter which is supported only in Chrome-like browsers.

Oh ok, sorry for the confusing there. I guess the best way would be the one shown in the demo then

**Comment by RobinLinus** [comment]
Just realized the multi-download is actually quite simple. Here's a first version 26352be478f4e6e98ed77979033dd782ce197456

**Comment by Bellisario** [comment]
So, what do you think about it? Files can be compressed in a single zip file with this library...
https://github.com/Stuk/jszip

**Comment by JFMugen** [comment]
> Just realized the multi-download is actually quite simple. Here's a first version [26352be](https://github.com/RobinLinus/snapdrop/commit/26352be478f4e6e98ed77979033dd782ce197456)

Just awesome :D

Thank you!

**Comment by RobinLinus** [comment]
> So, what do you think about it? Files can be compressed in a single zip file with this library...

Let's create a new issue for that #211
