### ISSUE TITLE
All Devices Visible

### ISSUE THREAD

**Issue by aaronpie** [RobinLinus/snapdrop#205]
I installed SnapDrop on a DigitalOcean droplet and everything seems to work, but when I had a friend navigate their device to my website we could see each other devices. These devices are not located on the same network. We were both connecting from our homes. I thought the devices could only be seen if you are on the same network.

**Comment by foxnoodles** [comment]
Wait what? How

**Comment by RobinLinus** [comment]
looks like something messes up the IPs seen by the server. Maybe the snapdrop runs behind a proxy which does sth funny with the HTTP headers?

**Comment by hello-smile6** [comment]
So, that means that Snapdrop is not secure. Were you able to send files?

**Comment by foxnoodles** [comment]
It's been more than 2 weeks and no word from the author. If this is true the whole concept of this app is donzo until further notice and even after that it will require a deep analysis to confirm that the issue was actually fixed for good.

**Comment by aaronpie** [comment]
Sorry for the late reply, but another friend of mine helped me solve the issue I was having with SnapDrop. It was Nginx Proxy Manager that was causing the issue. It appears by using NPM all users are seen as coming from the same IP address so SanpDrop believes were are on the same network. So SnapDrop was actually working correctly, but it was my setup that was causing the issue. After changing some settings in NPM, the problem has been fixed.

**Comment by Jay54520** [comment]
> Sorry for the late reply, but another friend of mine helped me solve the issue I was having with SnapDrop. It was Nginx Proxy Manager that was causing the issue. It appears by using NPM all users are seen as coming from the same IP address so SanpDrop believes were are on the same network. So SnapDrop was actually working correctly, but it was my setup that was causing the issue. After changing some settings in NPM, the problem has been fixed.

How did you config NPM to resolve this problem? I tried `proxy_set_header X-Forwarded-for $remote_addr;` and docker host mode of NPM but didn't resolve.
