### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by CDsigma** [RobinLinus/snapdrop#208]
I spent a couple hours coding and made a simple iOS app for Snapdrop. The source code can be found here: https://github.com/CDsigma/Snapdrop-iOS-App. The app is just a simple WebView that opens to the Snapdrop website.

I'd like to eventually publish the app to the iOS app store so people have an easier way to use and find Snapdrop on iOS. I still have to get the app to interact with the iOS files app so documents can be downloaded to an iOS device (which I'm not sure how to do right now) but all other key features currently work.

Just wanted to let you know 👍

**Comment by child-duckling** [comment]
Just have it open to a share sheet.

**Comment by fm-sys** [comment]
What about also adding this one to the FAQ?

**Comment by RobinLinus** [comment]
Thank you @CDsigma  
Added this to the FAQ. https://github.com/RobinLinus/snapdrop/blob/master/docs/faq.md
