### ISSUE TITLE
Security-Enhancement: Add Sender-ID to Message / Filetransfer

### ISSUE THREAD

**Issue by TxBase** [RobinLinus/snapdrop#21]
At the moment the Sender is anonymous.
In a public network with untrusted participants, it could be abused.
Receiving Files from an anonymous is potentially dangerous.

**Comment by 2br-2b** [comment]
This should be implemented along with #69

**Comment by PaulSzymanski** [comment]
The peers now have unique names: https://github.com/RobinLinus/snapdrop/pull/91
The receive modal still has no indication who send the file.
