### ISSUE TITLE
Potential Bugs and Anti-Patterns

### ISSUE THREAD

**Issue by HarshCasper** [RobinLinus/snapdrop#210]
## Description 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/snapdrop/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point of time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

Some of the notable issues are: 

- Undeclared Variables [here](https://deepsource.io/gh/HarshCasper/snapdrop/issue/JS-0125/)
- Unused Variables [here](https://deepsource.io/gh/HarshCasper/snapdrop/issue/JS-0128/)
- Redeclared Variables [here](https://deepsource.io/gh/HarshCasper/snapdrop/issue/JS-0085/)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

**Comment by RobinLinus** [comment]
Cool thank you! I'll see if I can fix these issues.
