### ISSUE TITLE
Use zip to transfer multiple files 

### ISSUE THREAD

**Issue by RobinLinus** [RobinLinus/snapdrop#211]
This issue came up when solving to #201.

Files can be compressed in a single zip file with this library. https://github.com/Stuk/jszip

See: 

- https://github.com/RobinLinus/snapdrop/issues/201#issuecomment-748889856
- https://stackoverflow.com/questions/18451856/how-can-i-let-a-user-download-multiple-files-when-a-button-is-clicked

**Comment by fm-sys** [comment]
I think we shouldn't zip the files for download as zip archives are way more difficult to handle than uncompressed files (especially on mobile devices!)

**Comment by RobinLinus** [comment]
Feels like the cost/gain ratio isn't great here. I'll close this issue for now.
