### ISSUE TITLE
Animation is stopping after sometime.

### ISSUE THREAD

**Issue by Krrishdhaneja** [RobinLinus/snapdrop#213]
@RobinLinus I found that animation stops after sometimes in the website.

**Comment by Krrishdhaneja** [comment]
Here is the link to the video(i uploaded it on onedrive) for reference ->
https://1drv.ms/v/s!AvYkgBwdAmFFdBkxlRxC9ZkCBbw

**Comment by Bellisario** [comment]
https://github.com/RobinLinus/snapdrop/blob/585a3d02fd2f69fa2afa99a02e9572e7d149ebf4/client/scripts/ui.js#L609

The animation stops because it has a timeout...
So, do you suggest a no-stop animation?

**Comment by fm-sys** [comment]
> So, do you suggest a no-stop animation?

Sounds reasonable. However, we should wait some time for feedback from others...

**Comment by Bellisario** [comment]
@RobinLinus what do you think?

**Comment by RobinLinus** [comment]
It is indeed the intended behavior. What is your suggestion? Should it fade out more smoothly?

**Comment by fm-sys** [comment]
> Should it fade out more smoothly?

Then it would at least look more intended...

**Comment by Jap2-0** [comment]
Agreed, I thought the page was frozen the first time I saw it.

**Comment by Krrishdhaneja** [comment]
I think it must be continuous @RobinLinus . Wouldn’t it look awesome?

**Comment by Krrishdhaneja** [comment]
Hey, I encountered another error, the logo of web app of @RobinLinus is looking weird! ->

![Screenshot_20201224-104450_One UI Home.jpg](https://user-images.githubusercontent.com/65185487/103062746-32595d00-45d5-11eb-848d-7e7e2e4f4e5d.jpg)

#### **Before ->**

![20201224_104721.jpg](https://user-images.githubusercontent.com/65185487/103062817-6b91cd00-45d5-11eb-8aa1-a1d3408b2ac4.jpg)

**Comment by Krrishdhaneja** [comment]
Merry Christmas everyone

**Comment by Krrishdhaneja** [comment]
Anything resolved about this @RobinLinus @fm-sys @Jap2-0 ?

**Comment by RobinLinus** [comment]
@Krrishdhaneja the issue with the app icons should be solved in e4d4742e80181576afba99e6423d2c7375807a8a

**Comment by RobinLinus** [comment]
Maybe we should run the animation until a peer joined?

**Comment by eroc1990** [comment]
Either that, or you could make it pulse instead of consistently animating, but once a peer is found the pulsing locks?

**Comment by Krrishdhaneja** [comment]
Isn't the new logo very similar with snapdrop-android?

**Comment by Krrishdhaneja** [comment]
Btw the problem of animation is fixed now , so thanks!
