### ISSUE TITLE
[Suggestion] Change the icon to something more rounded?

### ISSUE THREAD

**Issue by foxnoodles** [RobinLinus/snapdrop#220]
Basically what title says, the current App square icon looks outdated by todays trends and design languages used in most concurrent OSes.

**Comment by Bellisario** [comment]
I haven't understanded, why did you say square icon? Can you attach a photo of your suggestion? Thanks!

**Comment by foxnoodles** [comment]
<img width="221" alt="Screen Shot 2020-12-27 at 17 28 43" src="https://user-images.githubusercontent.com/1949828/103171886-fdfdcf00-4868-11eb-8f49-a9dec70fff2c.png">

When you install it as a chrome app, the icon is a simple square. Also it's kinda oversized.

**Comment by Bellisario** [comment]
Thanks again @foxnoodles, I've created a new pull request to resolve your ploblem.
When the pull request is closed, you'll need to "unistall" Snapdrop (PWA) and "re-install" it to change the icon.

**Comment by foxnoodles** [comment]
> Thanks again @foxnoodles, I've created a new pull request to resolve your ploblem.
> When the pull request is closed, you'll need to "unistall" Snapdrop (PWA) and "re-install" it to change the icon.

Thanks a lot!
