### ISSUE TITLE
Multiline messages support

### ISSUE THREAD

**Issue by poweruser82** [RobinLinus/snapdrop#223]
New line characters are stripped when sending messages between devices.

Tested on Safari 13.1.2 (13609.3.5.1.5) and Firefox 84.0.1 (64 bit) on macOS High Sierra and Safari on iOS 14.2.

New lines should be preserved.

**Comment by RobinLinus** [comment]
Looks like #202 introduced this bug... 
I'll have a look

**Comment by poweruser82** [comment]
Probably the problem could be solved using `innerText` instead of `textContent`
https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

**Comment by RobinLinus** [comment]
Thanks a lot for that hint. 6a5ad0f1fbe930b6953ba8b5f96a0e5964158c78 should fix that bug. Does that work for you?

**Comment by poweruser82** [comment]
It seems to work OK. Thank you very much 🙇
