### ISSUE TITLE
Transferring images changes format

### ISSUE THREAD

**Issue by apprehensivetarget** [RobinLinus/snapdrop#228]
When I try to transfer images from my iPhone to my Windows 10 pc, all images are received as jpeg, although the images are stored on iPhone in Adobe dng. This makes transferring images in their original format quite annoying as it doesn't work over snapdrop. Is there a way to stop the changing of formats when transferring over snapdrop?

**Comment by RobinLinus** [comment]
The format is probably not changed but the filename?

**Comment by RobinLinus** [comment]
There's certainly no code that would allow Snapdrop to convert file types. The conversion is probably some system feature. Most likely the iPhone converts the images when selecting or so?

**Comment by apprehensivetarget** [comment]
Oh ok, it must be my iPhone then. Everything else works perfectly fine and it's and amazing experience overall.
