### ISSUE TITLE
PWA maskable icon exceeds minimum safe zone

### ISSUE THREAD

**Issue by blueberrybrownie** [RobinLinus/snapdrop#235]
Snapdrop's logo in /images/android-chrome-192x192.png exceeds the minimum safe zone of a maskable icon and gets partially cut off when installed as a PWA on Android as a result. The image below from [maskable.app](https://maskable.app/?demo=https://snapdrop.net/images/android-chrome-192x192.png) demonstrates this.

![Screenshot 2021-01-01 at 10 56 13](https://user-images.githubusercontent.com/47041194/103437486-3530ff00-4c20-11eb-94a5-140ada8738ef.png)

My pull request adding padding to the logo as per [guidelines](https://web.dev/maskable-icon/) was reverted.

**Comment by RobinLinus** [comment]
ups, sorry! You are right, #222 overwrote #217. @bellsario could you fix that?

**Comment by blueberrybrownie** [comment]
Oh I'm sorry that was my fault! I didn't realise Chrome would use that icon on macOS

**Comment by RobinLinus** [comment]
It seems ridiculously hard to set proper app icons correctly cross-platforms. How can we fix that?

**Comment by RobinLinus** [comment]
Looks like the Android "standard" now also expects a background color, right? 
The iOS icon had the same issue and thus, looks different than the "regular" app icons: https://snapdrop.net/images/apple-touch-icon.png
However, a filled square looks weird as app icon on MacOS. 

How do other projects solve that isssues?

**Comment by blueberrybrownie** [comment]
It is ridiculous. There's no simple, set way to please every platform because there are so many and they change so fast. You can obey everyone's guidelines and be set for each edge-case but you end up with a thousand different icons.

Looking at Twitter, they have two sets of 192x192 and 512x512 icons, one with a [solid background colour](https://abs.twimg.com/responsive-web/client-web/icon-default-maskable.2fd29c85.png) to please Android's maskable icon shapes, and another ['normal' one](https://abs.twimg.com/responsive-web/client-web/icon-default.ee534d85.png) used for other platforms. They set the purpose as just "maskable" for the solid background ones in the manifest (rather than "any maskable"), and just don't declare a purpose for the normal set

**Comment by RobinLinus** [comment]
Twitter is a good example. I guess we should copy their approach.
