### ISSUE TITLE
Make Snapdrop a PWA

### ISSUE THREAD

**Issue by hello-smile6** [RobinLinus/snapdrop#238]
Go to Snapdrop in iOS Safari and run the bookmarklet javascript:document.getElementsByTagName(%22head%22)%5B0%5D.innerHTML=%22%22;document.write('%3Clink%20sizes=%22120x120%22%20rel=%22apple-touch-icon%22%20href=%22'+prompt(%22Icon%20URL%22)+'%22%3E%3Cscript%20async%20src=%22https://unpkg.com/pwacompat%22%20crossorigin=%22anonymous%22%3E%3C/script%3E%3Cmeta%20name=%22apple-mobile-web-app-capable%22%20content=%22yes%22%3E');document.body.innerHTML=%22%22;

To do that, bookmark any page and edit the URL to be the bookmarklet. Run it on Snpdrop and enter "images/apple-touch-icon.png" when prompted. Then, share as Add to Home Screen, fix the title, and Snapdrop becomes a PWA on your home screen just like any app.

**Comment by hello-smile6** [comment]
The link got messed up. Here it is, decoded.

> javascript:document.getElementsByTagName("head")[0].innerHTML="";document.write('<link sizes="120x120" rel="apple-touch-icon" href="'+prompt("Icon URL")+'"><script async src="https://unpkg.com/pwacompat" crossorigin="anonymous"></script><meta name="apple-mobile-web-app-capable" content="yes">');document.body.innerHTML="";

That should work.

**Comment by foxnoodles** [comment]
Thanks for the tip, though Snapdrop is already a PWA, I would suggest editing the title "[Tip] How to Add Snapdrop to your IOS home screen" or something along those lines.

**Comment by child-duckling** [comment]
you just press “add to home screen” in the share sheet...

**Comment by hello-smile6** [comment]
@child-duckling That won't work without the bookmarklet. I developed it for myself but chose to share it.

**Comment by F3000** [comment]
That has worked . Thanks

**Comment by hello-smile6** [comment]
> That has worked . Thanks

You're welcome. @RobinLinus should just get iOS download working.

**Comment by killtux** [comment]
whats the difference to just adding the link to snapdrop to home screen?

**Comment by hello-smile6** [comment]
> whats the difference to just adding the link to snapdrop to home screen?

Whether it shows in a browser tab.

**Comment by quacksire** [comment]
> > whats the difference to just adding the link to snapdrop to home screen?
> 
> 
> 
> Whether it shows in a browser tab.

offline capabilities too, when router disconnects from the internet but not the LAN

**Comment by hello-smile6** [comment]
> > > whats the difference to just adding the link to snapdrop to home screen?
> > 
> > 
> > Whether it shows in a browser tab.
> 
> offline capabilities too, when router disconnects from the internet but not the LAN

Signaling doesn't work in that environment. However, signaling could be accomplished via existing connections. In fact, in order to connect a device, you'd just have to manually connect two devices, even on a >1000-device network.

**Comment by 1ctinus** [comment]
@hello-smile6  does not work for me, how can I do this with other sites also?
