### ISSUE TITLE
Just thanks

### ISSUE THREAD

**Issue by kalafut** [RobinLinus/snapdrop#240]
I visited your donate link but also want to say: this utility has been incredibly useful for our household! The kids have school-issued iPads and Chromebooks that are incredibly locked down making it very tedious to get things on and off them (even printing doesn't work and has to be from some other device). This tool is by far the quickest, simplest way I've found to loop in dad or mom's computer as needed during more involved assignments. Thanks for your work on it!

**Comment by RobinLinus** [comment]
Thanks a lot! Great to hear Snapdrop is useful to you!
💪 🤓 ❤️
