### ISSUE TITLE
Show PWA in iOS share menu

### ISSUE THREAD

**Issue by ln-12** [RobinLinus/snapdrop#241]
First of all: snapdrop is awesome, thanks!

My suggestion/feature request is to add support for the iOS share menu (see below). It would make sharing files a lot easier, if one could simply tap "Snapdrop" next to the "AirDrop" icon. For now, I have to save the file somewhere on my device, open the webpage and search for that same file although the snapdrop PWA icon is on my homescreen.

![image](https://user-images.githubusercontent.com/36760115/103795636-84bf6280-5046-11eb-9490-5603fe6f7859.png)

**Comment by RobinLinus** [comment]
Unfortunately this is currently not possible with web apps.

**Comment by ln-12** [comment]
What about the [Web Share Target API](https://web.dev/web-share-target/)?

**Comment by RobinLinus** [comment]
Unfortunately, it is not available on iOS.

**Comment by ln-12** [comment]
I see, thanks. Maybe the native app (see [here](https://github.com/CDsigma/Snapdrop-iOS-App/issues/2) for the issue) can provide this functionality.

**Comment by RobinLinus** [comment]
Yeah, you have to ask them. I am not involved in this project.
