### ISSUE TITLE
DataChannel option 'reliable' is obsolete and shouldn't be used.

### ISSUE THREAD

**Issue by schlangguru** [RobinLinus/snapdrop#242]
https://github.com/RobinLinus/snapdrop/blob/b2e79913aa81f76a83ae163007a13dd45a69562a/client/scripts/network.js#L255
As the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/reliable) mention 'reliable' should be replaced with ['ordered'](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/ordered).

**Comment by RobinLinus** [comment]
Thanks for this hint!
