### ISSUE TITLE
Win10 to iPad (14.4) Files Fail to Send

### ISSUE THREAD

**Issue by LogicNg** [RobinLinus/snapdrop#263]
I knew it has [once happened](https://github.com/RobinLinus/snapdrop/issues/92) and at that time the problem was solved. I knew it isn't network problem because when I pass file from my Android phone to PC it works flawlessly. However, when I send images from my PC to iPad it doesn't work, below is the console ↓

![image](https://user-images.githubusercontent.com/53685306/109291946-9a8e1e80-7864-11eb-9c7b-83ff83b64953.png)

**Comment by Bellisario** [comment]
Thank you @LogicNg. This is a common problem to be still resolved (#258 #259 #252 #249 #247 #233 #261).
For now, the only thing that you can do is follow these steps and disconnect and then reconnect both the device to the network.
Sorry for the inconvenient...

**Comment by LogicNg** [comment]
There were many duplication so I closed this post 2 days ago... Driven by curiousity I retried just now and the image transferred successfully, was the bug fixed?

**Comment by Bellisario** [comment]
Hi @LogicNg, no the bug hasn't been resolved, you successfully transferred the files because the bug it's only sometimes and lasts only few minutes.
Instead, the background stops the execution after 1750ms of a peer connection, it's by design...

**Comment by LogicNg** [comment]
OIC
