### ISSUE TITLE
[feature request] send URLs

### ISSUE THREAD

**Issue by mixuala** [RobinLinus/snapdrop#265]
I use iMsg/airdrop to quickly send links between Mac/IOS devices—eg a zoom link. But the chromebook is off limits. It would be nice if it could play along with snapdrop.

**Comment by Bellisario** [comment]
Why did you say "chromebook is off limits"? Chromebooks uses Chrome that can be used with Snapdrop...

**Comment by mixuala** [comment]
Sorry, I meant that the Chromebook does not have an iMessage client.  I
tried snapdrop, but I could not find a way to send a text URL--just files
and photos.

**Comment by fm-sys** [comment]
You can use right a click to send text messages (like URLs)

**Comment by mixuala** [comment]
I’m looking from my iPhone and I can see how to browse and choose files.
But I don’t see the text message option. Am I missing something?

**Comment by fm-sys** [comment]
![Screenshot_20210304_211556](https://user-images.githubusercontent.com/64581222/110024843-e6dad200-7d2e-11eb-818c-68e07ad65cf2.jpg)

**Comment by mixuala** [comment]
Doh!  It works. Thanks
