### ISSUE TITLE
No Save dialog on Firefox OS 2.6

### ISSUE THREAD

**Issue by TitanNano** [RobinLinus/snapdrop#27]
It say the file has been received but the download to save the file to the device storage is never triggered. The following error apears in the console:

![screen shot 2016-07-11 at 19 59 29](https://cloud.githubusercontent.com/assets/4500858/16741073/016f7c8c-47a2-11e6-9677-5641dad53844.png)

EDIT: if I duplicate the anchor node and call the click() method in the console by my self the download starts. So I think it might be an issue with polymer intercepting the click() method.

**Comment by RobinLinus** [comment]
Guess I fixed it. Can you check it?
