### ISSUE TITLE
Doesn't work on Amazon Fire TV (Downloader app)

### ISSUE THREAD

**Issue by josemsanchezb** [RobinLinus/snapdrop#271]
I tried several times to send some .apk files to the Fire TV Stick but after tapping for downloading it, the download fails.

Amazon Fire TV Stick with Downloader app (https://www.amazon.es/AFTVnews-com-Downloader/dp/B01N0BP507/ref=sr_1_1?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=downloader&qid=1615463881&s=mobile-apps&sr=1-1)

**Comment by Bellisario** [comment]
@josemsanchezb, this is probably because your "browser" doesn't support (javascript) blob download but only direct download links.

**Comment by josemsanchezb** [comment]
May be that. Thank you so much  @Bellisario !!

**Comment by hello-smile6** [comment]
Could `data:` URLs be used to download?
