### ISSUE TITLE
Cannot find iPhone to Windows on local network all using WiFi

### ISSUE THREAD

**Issue by kenjibailly** [RobinLinus/snapdrop#274]
I have no complex network, it's pretty simple with no extra modifications on the router part except port forwarding.
I had it working before in this same network.

Problem is that I cannot find my pc when connecting with my iphone and vice versa. I tried multiple browsers, but no change.
I tried it behind a reverse proxy, local ip with port, http, https. None of it does the trick.

I installed snapdrop using docker. No errors to be found, everything loads without any problem.
There's no time out either.

I can find my own device though, when firing up snapdrop twice on the same device even in a different browser.

I've been trying for days now, but I don't understand what the problem could be. I run a bunch of docker containers and none have network problems.

Any help would be appreciated. I don't even know where to look anymore.

**Comment by steakhutzeee** [comment]
I have the same exact problem.

If my devices are connected in wireguard vpn to my host i can see the devices, but locally under the same network i have the same issue as OP.

**Comment by kenjibailly** [comment]
I resolved my issue with: https://github.com/RobinLinus/snapdrop/issues/266
