### ISSUE TITLE
Down

### ISSUE THREAD

**Issue by ueen** [RobinLinus/snapdrop#275]
www.isup.me/https://snapdrop.net

**Comment by fm-sys** [comment]
@RobinLinus please! We all need snapdrop that much ❤️

**Comment by tomuky2k** [comment]
If it is this useful, then we must have all donated to @RobinLinus?

[Donate to @RobinLinus via PayPal - to help cover server costs](https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=FTP9DXUR7LA7Q&source=url)

**Comment by Bellisario** [comment]
Hey @RobinLinus, this is the second time that there is this problem... what is that?
Please resolve!!! I :heart: this app!

**Comment by ueen** [comment]
I have donated ;)

**Comment by Ein-Tim** [comment]
Does anyone (here) know the cause of the downtime? 

@Bellisario 
You said that something like this happened before, may I ask you what was the cause the last time (sorry, I'm new to snapdrop & this community)?

**Comment by Bellisario** [comment]
@Ein-Tim I don't know the problem but [here](https://github.com/RobinLinus/snapdrop/issues/268#issuecomment-795454926) is what @RobinLinus writed...

**Comment by Armster15** [comment]
http://144.202.2.223:8080/
I downloaded the source code and hosted it here. I'll take it down when the regular website goes back up. It doesn't have HTTPS on it though and the PWA isn't configured, but I think it should be good for while the issue is being resolved.

**Comment by LuKres1** [comment]
> http://144.202.2.223:8080/
> I downloaded the source code and hosted it here. I'll take it down when the regular website goes back up. It doesn't have HTTPS on it though and the PWA isn't configured, but I think it should be good for while the issue is being resolved.

yo man, ty vm

**Comment by laf0rge** [comment]
given that [I assume] there is no state on the snapdrop server to replicate, wouldn't it be possible to set up multiple servers with round-robin DNS to make sure it doesn't go down with a single point of failure? Depending on required resources (traffic, CPU), I would be interested in hosting one such instance.

**Comment by Ein-Tim** [comment]
snapdrop.net seems to be back online!

See also: isup.me/snapdrop.net

**Comment by ueen** [comment]
Alright, issue solved, i guess :))

**Comment by Bellisario** [comment]
Very good, but... what were the problem @RobinLinus?

**Comment by ueen** [comment]
As you're all here, may i introduce the Firefox Addon i wrote, it can either 
- display snapdrop in a popup (default) or 
- always run in the background (activate in settings) and open notifications for received files/texts

I would love here what you think about it :)

PS: I refactored some code and included it in the Addon, which is released under a Mozilla Public License, version 2.0, let me know if theres an issue and something i can do about it.

Get it here https://addons.mozilla.org/de/firefox/addon/snapdrop-for-firefox/

Of course its open source https://github.com/ueen/SnapdropFirefoxAddon

**Comment by Bellisario** [comment]
Thanks @ueen, but... add the chrome version, too! :pleading_face:

**Comment by ueen** [comment]
I don't use chrome, but it's all webextension standard so it probably works in chrome, just grab the code and try it :)

**Comment by hello-smile6** [comment]
I could compile the crx, @ueen .

**Comment by ueen** [comment]
You're welcome :)

**Comment by sdooh393** [comment]
No

**Comment by julian-fairfax** [comment]
> As you're all here, may i introduce the Firefox Addon i wrote, it can either
> 
>     * display snapdrop in a popup (default) or
> 
>     * always run in the background (activate in settings) and open notifications for received files/texts
> 
> 
> I would love to hear what you think about it :)
> 
> PS: I refactored some code and included it in the Addon, which is released under a Mozilla Public License, version 2.0, let me know if theres an issue and something i can do about it.
> 
> Get it here https://addons.mozilla.org/de/firefox/addon/snapdrop-for-firefox/
> 
> Of course its open source https://github.com/ueen/SnapdropFirefoxAddon

This is amazing (and so is the Android app, but the website works fine too)! I really like the background feature. Thanks for making this!

**Comment by hello-smile6** [comment]
> You're welcome :)
> @hello-smile6 feel free to make a pull request with the crx or upload directly to chrome store (although you might have to remove pop-up mode due to CSP) EDIT: now released version 1.6 with optional popup in another window
> 
> @Bellisario i'm not familiar with PWA, but maybe that is already serving the same purpose for chrome

@ueen Do you want the `pem` file so you can do future releases? I don't have a Google account, so I can't submit it. But you could, even without a Chromium-based browser installed.
Note: Microsoft Edge is based on Chromium, Chrome's browser framework. If you have it installed, you could make a `.crx` to release on the Chrome Web Store yourself.

**Comment by ueen** [comment]
@hello-smile6 what's the pem file (if ok just add to PR)? Can the extension be installed when it isn't released in the store (for Firefox it has to be signed by Mozilla)?
I also don't have edge, but I think it's pretty good right know, so we'll see if there will be many updates.
Probably we should move this to the add-on page, so open an issue over there if further points need to be discussed :)

**Comment by hello-smile6** [comment]
@ueen It is the private encryption key. For chromium browsers >v40, it must be installed from the browser developer's extension store. The only exception is Edge, which accepts extensions from the Chrome Web Store.

**Comment by hello-smile6** [comment]
@ueen If you enable GitHub Discussions on your repository, you could use that.

**Comment by ueen** [comment]
Ok let's move over

**Comment by ueen** [comment]
@Bellisario Chrome is now also supported!
https://github.com/ueen/SnapdropFirefoxAddon
Although the installation right now is kinda tedious (it's manageable) - I will not be uploading it to Chrome Web Store (I'm not using Chrome, it costs money and there might be issues with CSP), but if anyone would like to do that, please contact me!

**Comment by Bellisario** [comment]
Thank you @ueen!

**Comment by ln-12** [comment]
It's down again

![image](https://user-images.githubusercontent.com/36760115/114536535-78ecc900-9c51-11eb-916b-f45d9d4a3605.png)

**Comment by Bellisario** [comment]
@Armster15 ,can you re-start the "emergency" server?

**Comment by Ein-Tim** [comment]
@ueen pls reopen the issue

**Comment by fm-sys** [comment]
@RobinLinus pls have a look

**Comment by edoardocomar** [comment]
https://downforeveryoneorjustme.com/snapdrop.net?proto=https

**Comment by hello-smile6** [comment]
@RobinLinus Please fix the server!

**Comment by MohammadAG** [comment]
I setup another temporary server up at http://mohammadag.com:8081/

Same limitations as @Armster15's server.

**Comment by Bellisario** [comment]
Thank you @MohammadAG!

**Comment by fm-sys** [comment]
Hooray! Snapdrop is up again 🎉

**Comment by RobinLinus** [comment]
Sorry guys, we accidentally killed the server but now it's up again!

**Comment by matteog24** [comment]
The [website](https://downforeveryoneorjustme.com/snapdrop.net?proto=https) is down again.

**Comment by Ein-Tim** [comment]
cc @RobinLinus

@ueen Can you reopen the issue?

**Comment by ueen** [comment]
Can't but it seems down again :(

**Comment by Bellisario** [comment]
For now I need to use [ShareDrop](https://sharedrop.io/)...  : (

**Comment by MohammadAG** [comment]
I had no reason to take down my backup, so it’s still up at http://mohammadag.com:8081/

**Comment by ueen** [comment]
Seems back up
