### ISSUE TITLE
Ability to preview image files before saving

### ISSUE THREAD

**Issue by Wierdio** [RobinLinus/snapdrop#286]
![image](https://user-images.githubusercontent.com/19418115/113656440-eacd7d00-9669-11eb-80af-9af469fae56d.png)

In the situation of that image, you should be able to see a preview of the image file before accepting. Maybe a limited preview of the image, similar to Apple's airdrop? 
![image](https://cdn.pocket-lint.com/r/s/1200x630/assets/images/153288-phones-news-feature-what-is-apple-airdrop-and-how-do-i-use-it-image1-fymau7ecam.jpg)

**Comment by Bellisario** [comment]
@Wierdio, good thing to be implemented!
Let's see if someone would like to add it...

**Comment by dewanhimanshu** [comment]
@Bellisario  I want to work on this issue

**Comment by fm-sys** [comment]
This issue is fixed now. Please close. 

BTW, how long does it take until the change occur on https://snapdrop.net?
