### ISSUE TITLE
Does it use data for transferring files

### ISSUE THREAD

**Issue by nivekithan** [RobinLinus/snapdrop#289]
Another apps like shareit, Xender does not use data( Internet usage) to transfer files. But I am not really sure weather this the same case regarding snapdrop?

**Comment by Bellisario** [comment]
Snapdrop uses [WebRTC](https://en.wikipedia.org/wiki/WebRTC), that is a [peer2peer](https://en.wikipedia.org/wiki/Peer-to-peer) connection.
All things that you transfer with these app and Snapdrop, requires a connection (for some can be also local, I think)... No peer2peer _connection_ can be made without a _connection_!

**Comment by nivekithan** [comment]
I think i might not wrote my question clearly. I will try again,

I have data plan which has a limit  3 GB/ per day, If I were to watch a youtube video then certain amount of data will be reduced from that 3 GB/ per day. I am asking If I were to share files using snapdrop then will data get reduced from my 3 GB/per day plan. In shareIt, Xender it wont happen.

**Comment by Bellisario** [comment]
Ok @nivekithan, modified my answer, sorry!

**Comment by nivekithan** [comment]
I am really sorry If I am asking you some basic question.  

I need to transfer a lot of  700mb video files from my phone to computer, the data usage for STUN wont take that much data right?

**Comment by Bellisario** [comment]
No, don't worry!
**; )**

**Comment by nivekithan** [comment]
Thanks 😃, I will close this issue
