### ISSUE TITLE
PWA Crashes when moved

### ISSUE THREAD

**Issue by tcconway** [RobinLinus/snapdrop#290]
On Brave V1.22.71.

1. Install the PWA
2. Drag the window using the titlebar
3. App crashes.

**Comment by Bellisario** [comment]
@tcconway, I think this is a Brave bug, because Snapdrop doesn't uses any window drag API...

**Comment by tcconway** [comment]
Closing issue. This was not a bug within Snapdrop. Rather, BetterSnapTool is closing Brave PWA Apps.
