### ISSUE TITLE
Down again? 

### ISSUE THREAD

**Issue by fm-sys** [RobinLinus/snapdrop#308]
@RobinLinus  https://snapdrop.net seems to be down again...

**Comment by Bellisario** [comment]
Yes, down again also for me!
For now, you can use my [node version](https://github.com/Bellisario/node-snapdrop) on Heroku: https://node-snapdrop.herokuapp.com/
:wink:

**Comment by fm-sys** [comment]
Seems to be fixed. Snapdrop is running again 🎉
