### ISSUE TITLE
Making a webview chrome extension to use Snapdrop directly as a chrome extension

### ISSUE THREAD

**Issue by Aarush-Goyal** [RobinLinus/snapdrop#314]
# I would like to work on a chrome extension that uses webview to open snapdrop inside an extension.

- I think ability to use snapdrop inside an extension would make it more handy.

**Comment by fm-sys** [comment]
Be aware that there already is a web extension for Chrome/Firefox

https://github.com/ueen/SnapdropFirefoxAddon

And an android app
https://github.com/fm-sys/snapdrop-android

I think such a extention is nothing which should be included into the official snapdrop repo.

**Comment by Aarush-Goyal** [comment]
Cool
