### ISSUE TITLE
website certificate error

### ISSUE THREAD

**Issue by 0maunz0** [RobinLinus/snapdrop#316]
Can't access the website:

This website’s security certificate has been revoked, so you can’t go there at this time.
Error Code: ERROR_INTERNET_SEC_CERT_REVOKED

**Comment by hayschan** [comment]
Same for me 
![iShot2021-06-11 20 44 37](https://user-images.githubusercontent.com/25737801/121688317-e607c800-caf5-11eb-8ae7-e326c645c761.jpg)

![iShot2021-06-11 20 44 46](https://user-images.githubusercontent.com/25737801/121688309-e30cd780-caf5-11eb-8a11-ab3008218b39.jpg)

**Comment by Bellisario** [comment]
Try with my node-snapdrop project site (it's the same as the original, but it uses only nodejs):
https://node-snapdrop.herokuapp.com/

**Comment by fm-sys** [comment]
Interesting though: for me it is working without problems. So maybe device or geo speciffic?

![Screenshot_20210611_174921_org mozilla firefox_copy_540x1170](https://user-images.githubusercontent.com/64581222/121713870-9917f780-cadd-11eb-8a3e-8021de5f6c0e.jpg)

**Comment by 0maunz0** [comment]
works fine on mobile (brave browser) but not on my pc (firefox or edge ;) )

**Comment by Krrishdhaneja** [comment]
I am having the same issue.
See screenshots below for reference->
![IMG_0807](https://user-images.githubusercontent.com/65185487/121726928-d6de4580-cb08-11eb-8a31-3ef31f6f50ee.png)
On my ipad👆

![IMG_2950](https://user-images.githubusercontent.com/65185487/121726993-f1b0ba00-cb08-11eb-86be-5277e4e0af60.png)
Same issue on the iphone👆

**Comment by PaulSzymanski** [comment]
Hey sorry, it seems caddy had a hiccup while renewing the certificate. I manually renewed it now. I need to investigate what happened...
