### ISSUE TITLE
Websocket error when WebRTC disabled

### ISSUE THREAD

**Issue by baek-sang** [RobinLinus/snapdrop#318]
Send file
Firefox 89 >>> iOS 14,15 Safari / Chrome ( WebRTC enabled )
```
# firefox about:config setting, disable WebRTC

media.peerconnection.enabled = false
media.peerconnection.turn.disable = true
media.peerconnection.use_document_iceservers = false
media.peerconnection.video.enabled = false
media.peerconnection.identity.timeout = 1
```

# Error
![sendfile_error](https://user-images.githubusercontent.com/69100154/121801484-7539ea80-cc72-11eb-8e34-5ac7a9961e6b.png)

```
Uncaught TypeError: this.peers[message.to].sendFiles is not a function
    _onFilesSelected https://snapdrop.net/scripts/network.js:398
    PeersManager https://snapdrop.net/scripts/network.js:367
    fire https://snapdrop.net/scripts/network.js:505
    _onFilesSelected https://snapdrop.net/scripts/ui.js:146
    _bindListeners https://snapdrop.net/scripts/ui.js:111
network.js:398:32
```

Do I need to enable webrtc unconditionally?

**Comment by Bellisario** [comment]
Yes @baek-sang, Snapdrop uses WebRTC to send files across devices, so, you need to enable it to do a file transfer. Unfortunately, you need to enable this for the entire browser, there isn't a way, that I know, to enable it only for a site...
