### ISSUE TITLE
snapdrop.net not working due to bad WebSocket URL

### ISSUE THREAD

**Issue by MShekow** [RobinLinus/snapdrop#327]
At the time of writing, snapdrop.net is disfunctional, at least on my machines. The reason is very simple: in `network.js` in `_endpoint()` the line
`const url = protocol + '://' + location.host + location.pathname + '/server' + webrtc;`
results in `wss://snapdrop.net//server/webrtc"` (note the double slashes in the path segment!) because `location.pathname` is `/`. This causes that the websocket cannot connect (HTTP status 404 being returned for that URL). By changing the `url` variable in the JS debugger (to  `wss://snapdrop.net/server/webrtc"`), I can get it to work again.

I get this problem on both Firefox and Chrome.

**Comment by josiahkeeler** [comment]
network.js:16 WebSocket connection to 'wss://snapdrop.net//server/webrtc' failed: 
_connect @ network.js:16
_onVisibilityChange @ network.js:80
(anonymous) @ network.js:10

Same errors as above. :)

**Comment by MoPaMo** [comment]
Same for me (even on the downloaded PWA)

**Comment by Yash089610** [comment]
Yes same for me.

**Comment by RobinLinus** [comment]
Sorry for the hiccup. Should be fixed.

**Comment by Bellisario** [comment]
Now works good for me! :wink:
