### ISSUE TITLE
File Transfer : sends the same file until browser kills the tab.

### ISSUE THREAD

**Issue by 4nkitd** [RobinLinus/snapdrop#334]
when sending a file to someone. he'll receive the same file constantly.

**Comment by carelinus** [comment]
Same problem here using Chrome on Android. Worked fine a few days ago.
Maybe a Chrome update broke something?

**Comment by kilviolluberes** [comment]
Same issue Chrome Android -> Chrome M1 MacOS.

Chrome Android -> M1 MacOS Safari works perfect.

**Comment by Orlandoke** [comment]
Same issue here, file notification is received repititively, a few times per second. 
Same issue between Android and PC but also between two PC's on the same LAN, both using Chrome for Windows.
Has become unusable.

**Comment by Poopooracoocoo** [comment]
can anyone identify what the issue is?

**Comment by 4nkitd** [comment]
after doing a bit of testing, i can say that issue is at the sender side app the file but don't acknowledge that transfer is complete and just repeats the same thing like it never cleared the ques after transferring the lat file.

**Comment by fm-sys** [comment]
Snapdrop is completely unusable with Chrome/Edge/AndroidWebview currently :-/

 Is there really no one who could debug into this issue and provide a fix? A fix would be simply amazing!

**Comment by danielehrhardt** [comment]
Same Problem

**Comment by 4nkitd** [comment]
after testing a few diff versions of the thing i

**Comment by carelinus** [comment]
My guess is that a recent change (not necessary a bug) in Chrome/Chromium broke Snap drop.

**Comment by maxpereira** [comment]
Also having the same issue. Happens in both Chrome 92.0.4515.131 (Official Build) (64-bit) (cohort: Stable) and Edge 92.0.902.67 (Official build) (64-bit)

**Comment by RobinLinus** [comment]
Sorry guys, very busy lately. Anybody who can debug what's the cause of this issue?

**Comment by danielehrhardt** [comment]
> Should be fixed now. Sorry for the downtime...

Still the same Issue.

**Comment by RobinLinus** [comment]
@danielehrhardt 

> > Should be fixed now. Sorry for the downtime...
> 
> Still the same Issue.

have you tried to clear your cache ?

On Windows `Strg + Shift + R`
On Mac `Cmd + Shift + R`

**Comment by danielehrhardt** [comment]
> @danielehrhardt 
> 
> > > Should be fixed now. Sorry for the downtime...
> > 
> > Still the same Issue.
> 
> have you tried to clear your cache ?
> 
> On Windows `Strg + Shift + R`
> On Mac `Cmd + Shift + R`

Yee
