### ISSUE TITLE
[BUG] .apk transfer from between PC and Mobile

### ISSUE THREAD

**Issue by jeffersoncheang** [RobinLinus/snapdrop#336]
I was trying to transfer an apk from my PC running WIndows 10 to my Android 11 phone. The pairing and file transferring seem perfectly till the point I clicked "Save" on my phone .

On my PC, the "file transfer completed" message stuttered at the bottom of the screen while on my phone it stucked at the "Save As" screen. I had to exit the app and checked in my File Manager to see if I received the apk. Turned out no, the apk wasn't transferred at all.

Anyone faced the same issue? Any workaround or apk transfer is not supported as of now?

**Comment by fm-sys** [comment]
> I had to exit the app

Which app did you used? Using a regular browser or https://github.com/fm-sys/snapdrop-android should solve the problem...

**Comment by jeffersoncheang** [comment]
Thanks! Resolved!
