### ISSUE TITLE
Problems between Snapdrop with iOS Safari browser and PWA Brave for Windows

### ISSUE THREAD

**Issue by dtantono** [RobinLinus/snapdrop#338]
Hi
I want to share a question with this piece of technology. I use PWA on Brave for Windows and connect it with iOS safari. So, my purpose is to send the screenshot on portrait format. But, the image is cover whole IPhone screen and there is no option to save it. Is it a bug?

**Comment by Bellisario** [comment]
I've tested with a big image: yes, it's a bug...
I'll try to make a change in these days.
For now, I suggest to you to send large images into a zip file, so, it doesn't make any preview and you can download all without any problem.
