### ISSUE TITLE
snapdrop.net is down

### ISSUE THREAD

**Issue by patatjenl** [RobinLinus/snapdrop#36]
Hi! The website is down: https://snapdrop.net/

It's returning the following error:

```
502 Bad Gateway
nginx/1.4.6 (Ubuntu)
```

**Comment by patatjenl** [comment]
This is related to #28 but since that issue has been closed, I've made this new issue.

**Comment by patatjenl** [comment]
Has been fixed: it's up, again. Thanks!

**Comment by odinho** [comment]
Down again.
