### ISSUE TITLE
WebRTC Server won't connect or host to or from other devices on the same Network

### ISSUE THREAD

**Issue by n3m** [RobinLinus/snapdrop#368]
[Device 1]
Platform: PC
OS: Windows 10
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Browser: Brave V1.31.88 (Oct 29, 2021)

[Device 2]
OS: iOS 15.1
Platform: iPhone 12 Pro Max
Browser: Safari / Brave Browser for iOS V1.32 (21.10.13.18)

[Details]:
Seems that any devices that tries to create a ws room is being blocked or not completing the first request. Seems like the connection is not being upgraded to WSS, and no headers are provided in the request.

[Problem]:
Unable to join / create a room to share files in a local shared network.

**Comment by gaoyaodad** [comment]
me too

**Comment by Tinyu-Zhao** [comment]
me too

**Comment by ytakapower** [comment]
yeah me to

**Comment by gaoyaodad** [comment]
It works now

**Comment by ytakapower** [comment]
> It works now

O yes I see it thank you

**Comment by n3m** [comment]
Issue seems to be resolved.

Don't know what changed.
