### ISSUE TITLE
can't find module ensure-files.js

### ISSUE THREAD

**Issue by willenwu21** [RobinLinus/snapdrop#37]
it's show me "Error: Cannot find module './tasks/ensure-files.js'" when i use gulp server.

module.js:472
    throw err;
    ^

Error: Cannot find module './tasks/ensure-files.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

so i don't know how to fix it.

**Comment by wwwjsw** [comment]
+1

**Comment by Speefictor** [comment]
I got a same problem

**Comment by RobinLinus** [comment]
I am sorry, but the dependencies are terribly outdated and I couldn't fix them in a day of work.
