### ISSUE TITLE
Issue sending and receiving

### ISSUE THREAD

**Issue by pablomarusich** [RobinLinus/snapdrop#374]
I've checked out open issues regarding adblock/uBlock origin issues while using the app but I've also tried [disabling not only adblockers but all extensions in the page](https://imgur.com/hnFG3tG). I haven't been able to send either files nor messages either way.

- Android phone to Windows PC connection: I've tried the android app, through the website (on the phone); Chrome, installing snapdrop as an extension in Chrome and firefox in the PC. Same results with different combinations. Everytime the connection is good as refreshing the site makes the device on the other end disappear and appear again.
- Both on the same wifi.
- No adblock on Chrome.
- No root / adblock afaik on android phone.

Not sure what additional information to provide, but happy to do so if needed (and explained how to or what is needed lol)

This had worked for me in the past, haven't used it in a while but not sure what changed.

**Comment by Noanker188** [comment]
I've been having the same issues with snapdrop for the past couple of days.

**Comment by pablomarusich** [comment]
Fixed now, changed android app on my phone and that fixed it.

After finding [this issue thread](https://github.com/RobinLinus/snapdrop/issues/337) regarding multiple snapdrop apps avaiable in the play store I noticed I had the version the user **Psydex** mentioned as being bugged, unmaintened, and worse than his. 

I instead uninstalled the app I had and **installed "Snapdrop for Android"**

**AVOID Snapdrop | ShareIt** and the headache.
