### ISSUE TITLE
Image preview still too large 

### ISSUE THREAD

**Issue by fm-sys** [RobinLinus/snapdrop#383]
On Chrome/Firefox for Android, I still have the issue that the preview is too high. I thought this was solved by #340 which was merged, didn't the fix work or is the server image currently simply outdated? 

@Bellisario as you provided the fix, can you give us a small hint? 

|||
-|-
![Screenshot_20211206_154514_org mozilla firefox](https://user-images.githubusercontent.com/64581222/144868275-11e0d430-3d20-46fc-82e4-d40bb1504221.jpg)|![Screenshot_20211206_154541_org mozilla firefox](https://user-images.githubusercontent.com/64581222/144868285-ddff037c-951b-424c-bc62-6c24c311a87a.jpg)

**Comment by fm-sys** [comment]
When looking at https://snapdrop.net/styles.css, it seems the fix is not yet included.

@RobinLinus can you update the server image?

**Comment by hello-smile6** [comment]
> When looking at https://snapdrop.net/styles.css, it seems the fix is not yet included.
> 
> @RobinLinus can you update the server image?

Why wouldn't it auto-update?

**Comment by fm-sys** [comment]
> > When looking at https://snapdrop.net/styles.css, it seems the fix is not yet included.
> > @RobinLinus can you update the server image?
> 
> Why wouldn't it auto-update?

Not sure, but the files do not match with the current state of master...
