### ISSUE TITLE
Does not work between win10 chrome and Android/IOS/HMS

### ISSUE THREAD

**Issue by ZhXZhao** [RobinLinus/snapdrop#387]
I started snapdrop on win10 chrome and Android Edge/IOS Safari/HMS Edge, but i can't find any device in the same LAN.

**Comment by yjmp14** [comment]
If you use Snapdrop in China, please make sure you didn't run any proxies or VPNs on your devices or router, the website won't work properly behind them.
 
If you didn't and it still not work, try my website [wulingate.com](https://www.wulingate.com) as an alternative. Also, do not use proxies or VPNs. If my website doesn't work either, please tell me and I'll help you find out what's going on.

**Comment by ZhXZhao** [comment]
Thanks. It works after turning off VPNs.

**Comment by ZhXZhao** [comment]
> If you use Snapdrop in China, please make sure you didn't run any proxies or VPNs on your devices or router, the website won't work properly behind them.
> 
> If you didn't and it still not work, try my website [wulingate.com](https://www.wulingate.com) as an alternative. Also, do not use proxies or VPNs. If my website doesn't work either, please tell me and I'll help you find out what's going on.

Thanks. It works after turning off VPNs.
