### ISSUE TITLE
Message for Robin

### ISSUE THREAD

**Issue by sahil5d** [RobinLinus/snapdrop#389]
Hi Robin, I'm Sahil
I happened to see your reddit post about Satoshi. Thx for citing me
I'd like to share something new
https://medium.com/@sahil50/im-the-spacex-intern-who-speculated-satoshi-is-elon-musk-there-is-more-to-the-story-1cd16604bef0

**Comment by hello-smile6** [comment]
That looks cool.

**Comment by RobinLinus** [comment]
> Hi Robin, I'm Sahil I happened to see your reddit post about Satoshi. Thx for citing me I'd like to share something new https://medium.com/@sahil50/im-the-spacex-intern-who-speculated-satoshi-is-elon-musk-there-is-more-to-the-story-1cd16604bef0

Added you to a private repo collecting hints...
