### ISSUE TITLE
https://snapdrop.net/ is down

### ISSUE THREAD

**Issue by edi9999** [RobinLinus/snapdrop#39]
https://snapdrop.net/ doesn't respond at all, is it expected ?

**Comment by DeerSpotter** [comment]
still down. I love this service, sucks that it is down.

**Comment by RobinLinus** [comment]
Snapdrop is up again!

**Comment by edi9999** [comment]
It seems down for me ...

**Comment by edi9999** [comment]
http://downforeveryoneorjustme.com/snapdrop.net
