### ISSUE TITLE
PWA on iOS not possible

### ISSUE THREAD

**Issue by F3000** [RobinLinus/snapdrop#397]
Hi , 

when I create a shortcut under iOS 15 on my homescreen , safari will open a new Tab instead of open a separated PWA View .

**Comment by hello-smile6** [comment]
https://github.com/RobinLinus/snapdrop/issues/238#issue-777721029


<!--[Make Snapdrop a PWA #238](https://github.com/RobinLinus/snapdrop/issues/238)

**Comment by hello-smile6** [comment]
@F3000 Use this.
http://txti.es/snapdrop-ios-install Just drag the link on the webpage into your bookmarks and tap it on Snapdrop.

**Comment by F3000** [comment]
@hello-smile6 that doesent work for me . How did you do this ?

**Comment by hello-smile6** [comment]
> @hello-smile6 that doesent work for me . How did you do this ?

Works on iOS 12. Maybe 15 changed. Just download all of the files needed and run your own copy with support. Change the websocket URL to use snapdrop.net .
