### ISSUE TITLE
Allow SnapDrop to be used on a local network only (local host) 

### ISSUE THREAD

**Issue by DeerSpotter** [RobinLinus/snapdrop#40]

**Comment by dmo-odoo** [comment]
This. Make it a Chrome extension ?
Would it be possible that if only one of the two people has it installed the other can type its local address to reach it ? It would be told to the user like the current "Short link" feature.

Like: 
"Open Snapdrop on other devices to send files" (That would be true if both have internet or, if they don't have internet, if both have the Chrome extension installed)
"Direct link: 192.168.1.42" (That would work even with no internet and with only one of the people having the extension installed)

Could it even be possible ?

**Comment by DeerSpotter** [comment]
it's almost as if you want a encrypted local folder transfer

**Comment by dmo-odoo** [comment]
Well, basically I want AirDrop but in the form of a Chrome extension that is required by only one of the two party so once you have it, it can be used on any device to share files with anyone.

I've made some research and it looks like there are Chrome extensions which can act as a web server, so wouldn't it be possible to bundle snapdrop and its node dependencies using browserify so that the server could be run from within a chrome extension ?

**Comment by nkoehring** [comment]
A way to do this would be to install this as an app that encapsulates the server as well as the web application and extend them with an auto discovery feature. This could work by simply let the server broadcast the local network with something that is recognizable by the application. This would also lay a foundation for other requested features like #80

**Comment by DeerSpotter** [comment]
Norman,

It seems like you know this method, which other apps have you seen do this
from which you gleaned this insight?

**Comment by nkoehring** [comment]
What I described was basically any Bonjour/ZeroConf/Avahi application. I couldn't find any browser based service discovery implementation though.

**Comment by hello-smile6** [comment]
What about using a local device such as a random printer for connection? All you need is a security certificate. It doesn't even need to be accepted by the browser.

**Comment by Bellisario** [comment]
If you use my [node-snapdrop](https://github.com/Bellisario/node-snapdrop) you need just start it and the local Snapdrop and will be available in your entire local network just going to this url:
http://**server-public-ip-address**_:server-port_
