### ISSUE TITLE
https://snapdrop.net/ seems to be down

### ISSUE THREAD

**Issue by johhansantana** [RobinLinus/snapdrop#415]
Anyone else?

**Comment by TGRush** [comment]
can confirm :/

**Comment by Bellisario** [comment]
Very strange, only WebSocket seems not to work, instead, page load seems to be, perfect.

**Comment by Jay2k21** [comment]
Any alternatives to snap drop? Right when I need it the most, server is down

**Comment by johhansantana** [comment]
you could probably get one server up and running in a few minutes if you know what you’re doing. 

https://github.com/RobinLinus/snapdrop/blob/master/docs/local-dev.md

**Comment by Bellisario** [comment]
> Any alternatives to snap drop? Right when I need it the most, server is down

You can try with my Node version of Snapdrop: https://github.com/Bellisario/node-snapdrop

**Comment by fm-sys** [comment]
@RobinLinus could you please have a look at this?

**Comment by jasonhe54** [comment]
> > Any alternatives to snap drop? Right when I need it the most, server is down
> 
> You can try with my Node version of Snapdrop: https://github.com/Bellisario/node-snapdrop

The version on heroku, is that using 'node index.js' or 'node index.js public'

**Comment by Bellisario** [comment]
It simply uses `node index.js` from start script, because Heroku automatically exposes the local server...

https://github.com/Bellisario/node-snapdrop/blob/f4fd17ee05de3670eb8d6958eb98e24ff897aee7/package.json#L7

**Comment by Racxie** [comment]
> > Any alternatives to snap drop? Right when I need it the most, server is down
> 
> You can try with my Node version of Snapdrop: https://github.com/Bellisario/node-snapdrop

Thank you! Though I'd like to ask: is there a way to run this off my PC (Windows 10) or my own server (Debian)?

**Comment by Jay2k21** [comment]
Thank y'all for the advices! 
This might be the wrong place to ask this next question, but anyone have an advice on what program/app to use for an android device as a NAS? I have an iPhone but would like to backup photos into my backup android device as a nas

**Comment by 6543** [comment]
just a frendly reminder this project still run with a buss factor of **1**!

-> #333

**Comment by jasonhe54** [comment]
> is there a way to run this off my PC (Windows 10) or my own server (Debian)?

Yea, if you read the readme.md file, it still you how to set it up locally.

**Comment by wideocean** [comment]
Seems to be working again.
