### ISSUE TITLE
Has anybody a compiled version of Snapdrop?

### ISSUE THREAD

**Issue by RobinLinus** [RobinLinus/snapdrop#42]
Has anybody a compiled version of http://Snapdrop.net ? 
Just wanted to fix the server, but can't compile it from the sources anymore...

**Comment by citrusui** [comment]
See #43.

**Comment by RobinLinus** [comment]
Thanks again @citrusui !! Unfortunately `vulcanize` was crucial so I needed to find another way:
https://web.archive.org/web/20160802232958/https://snapdrop.net/

**Comment by citrusui** [comment]
I'm not too familiar with `vulcanize`... what role does it play in this Polymer app?

**Comment by RobinLinus** [comment]
It bundles all the elements into a single file.
