### ISSUE TITLE
MacOS Monterey Mac not being discovered

### ISSUE THREAD

**Issue by oquidave** [RobinLinus/snapdrop#421]
I have using Snapdrop for a while now. However, since I upgraded to macOS Monterey, my Mac Mini stopped being discovered by other devices on the network. The iPhone running iOS 15 works just fine and it is discovered by other devices on the same network, but not the mac running MacOS version 12.2.1. What could be the issue?
![snapdrop-monterey](https://user-images.githubusercontent.com/5080353/158357193-dbd3a5e3-9e91-4270-8487-5fff50f8002a.png)

**Comment by fm-sys** [comment]
Apple has invented a new feature called iCloud Private Relay. If this is activated, Snapdrop is unable to detect other devices which are in the same network.

Can you please check whether it helps to disable all proxies and relays before using Snapdrop?

**Comment by oquidave** [comment]
iCloud Private Relay requires iCloud+ subscription which I don't have. So Private relay is not activated. I don't have any proxy or VPN activated.

![apple-id-preferences](https://user-images.githubusercontent.com/5080353/158558728-9c88358a-82cd-45c8-9fe4-2b1492660086.png)

**Comment by oquidave** [comment]
Hey, this seems to be working now without any issues!
