### ISSUE TITLE
This site can’t be reached (https://snapdrop.net/)

### ISSUE THREAD

**Issue by khyrulAlam** [RobinLinus/snapdrop#428]
![Screenshot from 2022-03-31 21-48-00](https://user-images.githubusercontent.com/26439209/161096672-ee50449a-02cb-468a-ab51-1924aabd686f.png)

**Comment by daycat** [comment]
yep. seems like server is not ping-able.
<img width="483" alt="Screen Shot 2022-03-31 at 13 15 26" src="https://user-images.githubusercontent.com/88031959/161112581-d541f656-4d69-498c-9953-eaf9e00da24c.png">

**Comment by pke** [comment]
@RobinLinus The server is down?

**Comment by RobinLinus** [comment]
sorry for the downtime. The server is up again.

**Comment by wideocean** [comment]
@RobinLinus Server seems to be down again.

**Comment by Bellisario** [comment]
> @RobinLinus Server seems to be down again.

Seems to work for me... :face_with_spiral_eyes:
