### ISSUE TITLE
Website is not working. 

### ISSUE THREAD

**Issue by tanmay380** [RobinLinus/snapdrop#436]

**Comment by cy-polo** [comment]
Yes, it does not work :/

**Comment by Bellisario** [comment]
Same problem for me...

For now, try using my [node-snapdrop](https://github.com/Bellisario/node-snapdrop) server: https://node-snapdrop.herokuapp.com/

**Comment by Bellisario** [comment]
@RobinLinus, is there any server issue? Can you check? Thanks a lot...

**Comment by RobinLinus** [comment]
Restarted the server. Should be up again. Thanks for the hint!

**Comment by PandoraHayami** [comment]
Is the server dead again?

**Comment by fm-sys** [comment]
@RobinLinus can you check the server?

**Comment by Wig-gul** [comment]
Site/server still seems to be down

**Comment by fm-sys** [comment]
Why are there so many downtimes recently? Is it an Out of Memory crash caused by too many users or is there any other clue what's happening?
