### ISSUE TITLE
Snapdrop down

### ISSUE THREAD

**Issue by dereineLauch** [RobinLinus/snapdrop#445]
The [Website ](http://www.snapdrop.net/)doesent load, why?
I'm from Germany.
Is it just me?
![image](https://user-images.githubusercontent.com/84781281/167207629-5dc09350-135d-4522-8e72-9406da8af139.png)

**Comment by dereineLauch** [comment]
Ok, it seems like it's not just me: downforeveryoneorjustme.com/snapdrop.net

**Comment by hermanTenuki** [comment]
Yeah, same for me

**Comment by sarrietav-dev** [comment]
It's up

**Comment by RobinLinus** [comment]
Sorry guys, the server sometimes breaks when there is too much traffic. Should be up again.
