### ISSUE TITLE
Snapdrop is down

### ISSUE THREAD

**Issue by Sussy-OS** [RobinLinus/snapdrop#449]
Currently, Snapdrop is down, but not on the downloadable linux app.. probably a glitch, but the website is down.

**Comment by h4mmad** [comment]
Yeah can't access it

**Comment by deftdawg** [comment]
Down for me as well

```sh
~ $ curl https://snapdrop.net
curl: (7) Failed to connect to snapdrop.net port 443 after 5206 ms: Connection refused
```

**Comment by RobinLinus** [comment]
Sorry for the downtime. The server should be up again.
