### ISSUE TITLE
snapdrop.net is offline

### ISSUE THREAD

**Issue by Rihcus** [RobinLinus/snapdrop#450]
snapdrop.net went offline recently can't acess the site and pwa's report offline.

https://www.isitdownrightnow.com/snapdrop.net.html

**Comment by homemadestea58** [comment]
@RobinLinus Hey there! I just noticed this as well. Any idea why?

**Comment by hello-smile6** [comment]
The server's refusing connections on ports 80 and 443, did the webserver go down?
The server's accepting connections on port 22, so it's definitely online.
```
Starting Nping 0.7.80 ( https://nmap.org/nping ) at 2022-05-27 01:11 UTC
SENT (0.0028s) Starting TCP Handshake > snapdrop.net:80 (3.65.209.114:80)
RCVD (0.1428s) Possible TCP RST received from 3.65.209.114:80 --> Connection refused
SENT (1.0050s) Starting TCP Handshake > snapdrop.net:80 (3.65.209.114:80)
RCVD (1.1451s) Possible TCP RST received from 3.65.209.114:80 --> Connection refused
SENT (2.0062s) Starting TCP Handshake > snapdrop.net:80 (3.65.209.114:80)
RCVD (2.1464s) Possible TCP RST received from 3.65.209.114:80 --> Connection refused
SENT (3.0076s) Starting TCP Handshake > snapdrop.net:80 (3.65.209.114:80)
RCVD (3.1469s) Possible TCP RST received from 3.65.209.114:80 --> Connection refused
SENT (4.0093s) Starting TCP Handshake > snapdrop.net:80 (3.65.209.114:80)
RCVD (4.1492s) Possible TCP RST received from 3.65.209.114:80 --> Connection refused

Max rtt: N/A | Min rtt: N/A | Avg rtt: N/A
TCP connection attempts: 5 | Successful connections: 0 | Failed: 5 (100.00%)
Nping done: 1 IP address pinged in 4.15 seconds
```

**Comment by BlazeFrog** [comment]
I Used it like 4-5 days ago and it was working. Today I tried to use it and didn't work. Someone post this link saying he was hosting it but I don't trust it https://snapdrop.k26.ch/ prefer to use wormhole until fixed (too busy to find out how to host).

**Comment by hello-smile6** [comment]
> I Used it like 4-5 days ago and it was working. Today I tried to use it and didn't work. Someone post this link saying he was hosting it but I don't trust it https://snapdrop.k26.ch/ prefer to use wormhole until fixed (too busy to find out how to host).

I'll deploy an instance.

**Comment by hello-smile6** [comment]
@BlazeFrog Try this one, https://snapdrop.9pfs.repl.co/
Wormhole doesn't send files directly.

**Comment by BlazeFrog** [comment]
@hello-smile6 Yeah I know but snapdrop is down. I have a web page running with reverse proxy (apache) but not sure how to have a second one. For now I'll trust your address. Thank you very much! :)

**Comment by hello-smile6** [comment]
> @hello-smile6 Yeah I know but snapdrop is down. I have a web page running with reverse proxy (apache) but not sure how to have a second one. For now I'll trust your address. Thank you very much! :)

@BlazeFrog My server is using https://snapdrop-backend.9pfs.repl.co/ (`cd server/;npm i;node index.js`) for the backend, and https://npmjs.com/package/serve for the frontend server (`npx serve -n -C -s client/`), just so you know how it's configured.
## Modifications

- Changed websocket URL to point to my other server
> https://github.com/RobinLinus/snapdrop/blob/724f0af576852517bbea96a5d41302719ea514ec/client/scripts/network.js#L61
> 
```diff
-         const url = protocol + '://' + location.host + location.pathname + 'server' + webrtc;
+         const url = protocol + '://' + "snapdrop-backend.9pfs.repl.co" + '/server' + webrtc;
```

That's exactly what I've changed.

**Comment by hello-smile6** [comment]
I just added analytics using https://counter.dev/ , just so I have an idea of how much my server is being used, in case I need to change something.

**Comment by Rihcus** [comment]
> @BlazeFrog Try this one, https://snapdrop.9pfs.repl.co/ Wormhole doesn't send files directly.

Wormhole is kinda a hybrid of snap drop and standard upload. Files 5gb and bellow are uploaded although they can be sent via p2p as they are being uploaded simultaneously. Files 5-10gb soley rely on p2p and require tab to be open.

**Comment by Rihcus** [comment]
> I Used it like 4-5 days ago and it was working. Today I tried to use it and didn't work. Someone post this link saying he was hosting it but I don't trust it https://snapdrop.k26.ch/ prefer to use wormhole until fixed (too busy to find out how to host).

https://www.sharedrop.io/ is another alternative similar to snap drop that uses webrtc. One additional benefit is if you are on a large network or on different networks it works by sharing a room link.

**Comment by BlazeFrog** [comment]
@Rihcus We are talking about https://github.com/magic-wormhole/magic-wormhole it is a different project. that uses turn server or directly p2p if you are on LAN. what you are talking is a server that temporarily holds the data on an encrypted way https://github.com/SocketDev/wormhole-crypto

**Comment by hello-smile6** [comment]
> > @BlazeFrog Try this one, https://snapdrop.9pfs.repl.co/ Wormhole doesn't send files directly.
> 
> Wormhole is kinda a hybrid of snap drop and standard upload. Files 5gb and bellow are uploaded although they can be sent via p2p as they are being uploaded simultaneously. Files 5-10gb soley rely on p2p and require tab to be open.

I know.

**Comment by hello-smile6** [comment]
> @Rihcus We are talking about https://github.com/magic-wormhole/magic-wormhole it is a different project. that uses turn server or directly p2p if you are on LAN. what you are talking is a server that temporarily holds the data on an encrypted way https://github.com/SocketDev/wormhole-crypto

No, they're meaning https://wormhole.app/

**Comment by dtantono** [comment]
yeah the fork wulingate is also offline too

**Comment by Rihcus** [comment]
snapdrop.net is back online :)
