### ISSUE TITLE
SnapDrop Down

### ISSUE THREAD

**Issue by SaadhJawwadh** [RobinLinus/snapdrop#451]
The site is down for me

**Comment by Waldorf3** [comment]
Same here

**Comment by Waldorf3** [comment]
Up again now.

**Comment by hello-smile6** [comment]
If it goes down again, you could use my instance. https://snapdrop.9pfs.repl.co/

**Comment by KTachibanaM** [comment]
Still down for me :(

**Comment by ThatOneCalculator** [comment]
Down again...

**Comment by RobinLinus** [comment]
It's up again.

**Comment by ThatOneCalculator** [comment]
> It's up again. 

What hardware/provider is it being hosted on? If you want I could provide a VPS to host it on :)

**Comment by RobinLinus** [comment]
> > It's up again.
> 
> What hardware/provider is it being hosted on? If you want I could provide a VPS to host it on :)

Currently it runs on AWS and costs like $80/month

**Comment by RobinLinus** [comment]
Good question. Maybe too many connections? @PaulSzymanski what's your guess?
