### ISSUE TITLE
Snapdrop.net down another time

### ISSUE THREAD

**Issue by Bellisario** [RobinLinus/snapdrop#463]
@RobinLinus, seems [snapdrop.net](https://snapdrop.net/) is down another time...
Tested also here: https://isitup.org/snapdrop.net

**Comment by Bellisario** [comment]
If this is a problem of too much users at the same time, a thing could help is to limit user requests per minute (theoretically the main  page should not be continuously loaded) and so, for example, limit to 30 requests for minutes (on the main page) with an express library.
I think my purpose could solve the issue because might be there are some requests not really made to use the app but just to "try" shutdown the site (DDoS attack maybe).

**Comment by Bellisario** [comment]
Seems now it's up again!
Please @RobinLinus, have a look at the comment above :point_up:

**Comment by ln-12** [comment]
Well, for now it's down again.

**Comment by Bellisario** [comment]
Seems up now... :face_with_spiral_eyes:

**Comment by RobinLinus** [comment]
up again
