### ISSUE TITLE
Is it down again?

### ISSUE THREAD

**Issue by fzyzcjy** [RobinLinus/snapdrop#474]
https://snapdrop.net/

ERR_FAILED when visiting via chrome

**Comment by Bozic421** [comment]
Yes im having same issue it keeps saying connection lost

**Comment by MrConorAE** [comment]
Also not connecting here. "Problem loading page - Unable to connect" on Firefox.

Pinging the domain returns no reply - so it looks like the server it's hosted on is down, not just the frontend. If that's the case, then it may be entirely out of RobinLinus' control, unfortunately :(

**Comment by Bellisario** [comment]
Now seems to be working for me...
Anyway, I think a rate limit should be introduced to keep server safe...

---
cc. @RobinLinus

**Comment by fzyzcjy** [comment]
Work for me as well now

**Comment by fzyzcjy** [comment]
Seems to down again? :(

**Comment by Bellisario** [comment]
For me seems to be up another time… very strange! 😢

**Comment by asadm** [comment]
It's down again.
I have put up a mirror that I plan to maintain and improve: https://airdope.io/

**Comment by Bozic421** [comment]
> It's down again. I have put up a mirror that I plan to maintain and improve: https://airdope.io/
Thank you so much !!

**Comment by richmidwinter** [comment]
Down for anyone else?

**Comment by Bellisario** [comment]
Not for me
