### ISSUE TITLE
Snapdrop is down, again

### ISSUE THREAD

**Issue by savethekiddes** [RobinLinus/snapdrop#479]
It just seems that in these days snapdrop goes down in the afternoon for like half an hour and more. It is getting really annoying. Could you (@RobinLinus) deal with the hosting provider that is in charge of snapdrop.net for avoiding unexpected service shortages? Thank you.

**Comment by Bellisario** [comment]
Strangely seems only Socket connection to the server is down, the page it's loading correctly (with the only socket error).

**Comment by savethekiddes** [comment]
Snapdrop is now fully online
