### ISSUE TITLE
Files don't transfer between iPhone & computer

### ISSUE THREAD

**Issue by mollyr1** [RobinLinus/snapdrop#48]
Texts send to any device, but files do not. Using iPhone with Chrome & laptop with Chrome, or iPhone to iPhone, file claims to download, but doesn't. On computers, after agreeing to the download, nothing happens. On the iPhone, after agreeing to the download I get the option to open the file (which I click), but it opens a blank website (about:blank). Is there a fix? No issues transferring computer to computer.

**Comment by alexwhittemore** [comment]
Same. Further, I notice trying to send iOS>Windows 10/Chrome, the iOS device momentarily disappears from the Chrome snapdrop instance when I click "accept file"

**Comment by PaulSzymanski** [comment]
Resolved

**Comment by frol** [comment]
iOS -> Computer (Linux, Firefox) works fine, but the other way around (* -> iOS) has an issue with the blob file, it feels like Safari does not support blob protocol:

**Comment by frol** [comment]
I think this may help: https://stackoverflow.com/questions/24485077/how-to-open-blob-url-on-chrome-ios/24531108#24531108
