### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by imh1kiko** [RobinLinus/snapdrop#480]
Both laptop ("unable to connect") and phone ("connection lost") are timing out.

**Comment by Bellisario** [comment]
Duplicate of #474.

**Comment by Bellisario** [comment]
Seems to be down also for me...

**Comment by imh1kiko** [comment]
Seems fine for now.

**Comment by deplorable76** [comment]
unable to connect, site down?

**Comment by Bellisario** [comment]
Seems to be up now...

**Comment by asadm** [comment]
It's down again.
I have put up a mirror that I plan to maintain and improve: https://airdope.io/

**Comment by jimmy6DOF** [comment]
> It's down again. I have put up a mirror that I plan to maintain and improve: https://airdope.io/

just a quick note that discovery is not working for me mobile to pc but great idea and good way to support the app and Robin

**Comment by Ein-Tim** [comment]
Currently I don't encounter any problems accessing https://snapdrop.net.

Could you please check if the problem is resolved @imh1kiko?
