### ISSUE TITLE
Site isn't working

### ISSUE THREAD

**Issue by fluentmoheshwar** [RobinLinus/snapdrop#483]
![image](https://user-images.githubusercontent.com/65463913/184894431-3353eac4-3547-4124-885d-b9e6ddb46527.png)

**Comment by Bellisario** [comment]
For me seems the page loads, but it's unable to connect WebSocket with the server...

---

cc. @RobinLinus

**Comment by fluentmoheshwar** [comment]
> For me seems the page loads, but it's unable to connect WebSocket with the server...
> 
> cc. @RobinLinus

you probably have it cached. site loads on my phone but not pc

**Comment by Bellisario** [comment]
@fluentmoheshwar, confirmed.
I wasn't remembering Snapdrop has a service worker caching all... :face_with_spiral_eyes:

**Comment by fluentmoheshwar** [comment]
I think the server died

**Comment by kevstrat** [comment]
I'm getting the same error message. Quick note - I posted a YouTube video this morning promoting the service and that sent some additional traffic to the service (about 15K views this morning). Lots of comments are coming in about the service being unavailable.

**Comment by fluentmoheshwar** [comment]
> I'm getting the same error message. Quick note - I posted a YouTube video this morning promoting the service and that sent some additional traffic to the service (about 15K views this morning). Lots of comments are coming in about the service being unavailable.

I am also from your video. Was working perfectly before afternoon.

**Comment by Bellisario** [comment]
@kevstrat I just watched your video! Very beautiful...
I was thinking, if you and @RobinLinus agree, to add this to README so people want learn how works and how to use can also watch your video instead of reading all the complicated text...

**Comment by kevstrat** [comment]
Thanks! Absolutely, feel free to add the video to the README, as long as @RobinLinus is on board. From reading through the issues, there appear to be periodic outages without full explanation. This seems like P0 area to invest in. Let me know if there's anything I can do to help.

**Comment by asadm** [comment]
I have put up a mirror that I plan to maintain and improve: https://airdope.io/

**Comment by fluentmoheshwar** [comment]
> @kevstrat I just watched your video! Very beautiful...
> I was thinking, if you and @RobinLinus agree, to add this to README so people want learn how works and how to use can also watch your video instead of reading all the complicated text...

Readme.md don't support YouTube videos.

**Comment by Bellisario** [comment]
@fluentmoheshwar, I know... we may add just a link or the video thumbnail which you can click as a link...

**Comment by fluentmoheshwar** [comment]
The site is live!

**Comment by kevstrat** [comment]
That’s great to hear. What caused the outage? Is it worth a postmortem to prevent a reoccurrence?

On Aug 17, 2022, at 4:27 AM, Moheshwar Amarnath Biswas ***@***.***> wrote:

﻿

Closed #483<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRobinLinus%2Fsnapdrop%2Fissues%2F483&data=05%7C01%7C%7C3852e20b2b124255367408da804384db%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637963324714462280%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ntgeCo3vdHNwlyRkXj8mz6XebItnjmed8DnylcBNXvQ%3D&reserved=0> as completed.
