### ISSUE TITLE
the Site have been down for the last 24 hours.

### ISSUE THREAD

**Issue by harrysof** [RobinLinus/snapdrop#485]

**Comment by Bellisario** [comment]
Yes, also for me...
I suggest to use my [node-snapdrop](https://github.com/Bellisario/node-snapdrop) server waiting @RobinLinus's server to come back online:
https://node-snapdrop.herokuapp.com/

**Comment by Ein-Tim** [comment]
Currently I don't encounter any problems accessing https://snapdrop.net.

Could you please check if the problem is also resolved for you @harrysof?

**Comment by harrysof** [comment]
Yes Thank you so much for replying, the website is working flawlessly ever
since the issue comment.
