### ISSUE TITLE
snapdrop.net is down

### ISSUE THREAD

**Issue by floriandejonckheere** [RobinLinus/snapdrop#500]
The server at https://snapdrop.net/ does not seem to respond.

**Comment by Bellisario** [comment]
Seems to work for me now

**Comment by floriandejonckheere** [comment]
Seems to be working now indeed.

**Comment by vanshg** [comment]
Seems to be down again?

**Comment by Bellisario** [comment]
Up for me, maybe there some small downtimes very often…

@RobinLinus, any solution?

**Comment by RobinLinus** [comment]
> Up for me, maybe there some small downtimes very often…
> 
> @RobinLinus, any solution?

Haven't had time to look into it yet. I guess the server's WebSocket implementation has some kind of bug which crashes it.
