### ISSUE TITLE
Is it possible to disable/hide the ripple effect?

### ISSUE THREAD

**Issue by pqnhan** [RobinLinus/snapdrop#501]
On some of my older devices, every time I open the snapdrop, it's usually frozen by ripples spreading across the screen.
I know the added effect makes a good impression, but if it can be turned off somehow for weak devices that would be great.

I wonder is it possible to disable it temporarily using uBlock's filter for example?

**Comment by Bellisario** [comment]
@pqnhan, that's possible with uBlock Origin!
For example, adding this on "My Filters" section:
```
snapdrop.net##canvas
```

> **P.S.:** Always remember if Snapdrop code changes, this could fail to match or (worse) broke some needed element.

**Comment by pqnhan** [comment]
thanks, I'll check again if the filter doesn't match when the code changes.
