### ISSUE TITLE
Snapdrop website is down.

### ISSUE THREAD

**Issue by samuelwhiskeyjohnson** [RobinLinus/snapdrop#505]
![image](https://user-images.githubusercontent.com/71688370/192083902-e4d12ad8-728d-4cef-9e74-e34d644a8913.png)

**Comment by PikiPCMR** [comment]
i have the same problem, in all of my devices with all types of connections.

**Comment by newleon8** [comment]
Snapdrop site is down here too.

**Comment by cy-polo** [comment]
Hello @RobinLinus, I confirm that your website is down!

**Comment by danielehrhardt** [comment]
https://filedrop.codext.de/

**Comment by chengzi-bamao** [comment]
the largest file that the website can transfer is???

**Comment by danperks** [comment]
I can access it now, so assuming this resolved itself.

**Comment by Crazypersonalph** [comment]
Snapdrop is down once again

**Comment by virtuallysarvad** [comment]
Yup for me too!

**Comment by RobinLinus** [comment]
should be up again
