### ISSUE TITLE
snapdrop.net is down. 

### ISSUE THREAD

**Issue by xigolle** [RobinLinus/snapdrop#507]
I cannot seem to reach the site at http://snapdrop.net/
![image](https://user-images.githubusercontent.com/4833546/193648696-22fc2dc1-1879-4265-a9c4-97e504254b1d.png)

**Comment by ikifar2012** [comment]
Same here, it appears to be down and with little activity on the project, it may be time to fork

**Comment by mmwelt** [comment]
It's not just the code of the project, it's also about setting up and paying for a running instance.

**Comment by 6543** [comment]
#333 ... well looks like :/

**Comment by svenjacobs** [comment]
What a pity. I just recently discovered Snapdrop and thought this is a great application for sharing files between devices. There are alternatives like [croc](https://github.com/schollz/croc) or [magic-wormhole](https://github.com/magic-wormhole/magic-wormhole). However not so user friendly, especially on mobile devices.

**Comment by 6543** [comment]
Make libredrop ;)

**Comment by 6543** [comment]
The thin is, i wont push forward on it, as i dont plan to maintain it as i already do to a lot of foss

**Comment by RobinLinus** [comment]
the server is up again!
