### ISSUE TITLE
Add Instances Page

### ISSUE THREAD

**Issue by Noahs-Git** [RobinLinus/snapdrop#510]
Since I sometimes experience problems with the official site (and I am probably not the only one), I would suggest to add an instances page to this project, so that the users can easily pick a different server, in case the main server causes problems.

For now I could find the following instances, searching on Github (including non-depreciated forks):
https://snapdrop.net/ (Official, Version: Oct5/2022)
https://snapdrop.k26.ch/ (Version: ?)
https://snapdrop.9pfs.repl.co/ (Version: ?)
https://filedrop.codext.de/ (Version: ?)
https://s.hoothin.com/ (fork, 19 stars)
https://www.wulingate.com/ (fork, 15 stars)
https://snapdrop.fairysoft.net/ (fork)
https://airtransferer.web.app/ (fork)

**Comment by Bellisario** [comment]
I think these can be added on another section adjacent to this one:
https://github.com/RobinLinus/snapdrop/blob/master/docs/faq.md#third-party-apps

For example, my Node version could be added here, too, instead of the app section…

***

@RobinLinus what do you think?

**Comment by RobinLinus** [comment]
> I think these can be added on another section adjacent to this one:
> https://github.com/RobinLinus/snapdrop/blob/master/docs/faq.md#third-party-apps

sounds good! thank you
