### ISSUE TITLE
Snap Drop Connection Lost

### ISSUE THREAD

**Issue by Ee465** [RobinLinus/snapdrop#540]
Snapdrop does not load and keeps saying the connection is lost. 
![scrnli_11_21_2022_10-47-15 AM](https://user-images.githubusercontent.com/109324982/203112493-79f5b483-c401-42df-b1d8-150d87047b90.png)

**Comment by danielehrhardt** [comment]
Disable iCloud Private Relay 
https://filedrop.codext.de/

**Comment by RobinLinus** [comment]
@danielehrhardt please stop spamming!
