### ISSUE TITLE
Snapdrop is down (again)

### ISSUE THREAD

**Issue by Crazypersonalph** [RobinLinus/snapdrop#541]
Here we go again

**Comment by Bellisario** [comment]
Currently down also for me.

**Comment by Crazypersonalph** [comment]
Back up now

**Comment by megaroeny** [comment]
Was down for me, for a while yesterday, then back up. Today it's down again.

**Comment by Bellisario** [comment]
Also for me

**Comment by Crazypersonalph** [comment]
Re-opened due to the site being down again

**Comment by RobinLinus** [comment]
restarted.

**Comment by Crazypersonalph** [comment]
Snapdrop connection lost, for me at least, seems to be problem with servers

**Comment by Crazypersonalph** [comment]
network.js:16 WebSocket connection to 'wss://snapdrop.net/server/webrtc' failed: 
WS: server disconnected
