### ISSUE TITLE
snapdrop.net is down

### ISSUE THREAD

**Issue by FarukOzderim** [RobinLinus/snapdrop#561]
curl snapdrop.net

curl: (7) Failed to connect to snapdrop.net port 80 after 97 ms: Connection refused

**Comment by Bellisario** [comment]
Confirm. Down also for me...
https://isitup.org/snapdrop.net

**Comment by yarub123** [comment]
Same here 1/14/23, 1:31 AM. Tried all the instances as well. Probably a server issue.

**Comment by simpleapples** [comment]
same for me 15/01/23

**Comment by Bellisario** [comment]
Down also today... 😢

**Comment by RobinLinus** [comment]
up again
