### ISSUE TITLE
Downloaded files are flagged as potentially unwanted by microsoft. Need to click 'keep' for each one.

### ISSUE THREAD

**Issue by rmpasswd** [RobinLinus/snapdrop#573]
Microsoft flags the files as potentially unwanted, need to click keep them anyway for each time:

>This is a potentially unwanted app Microsoft Defender SmartScreen reported that this app has a low reputation or might cause unexpected behaviors. 
> Name: DSC 0015JPG (this is the image file name)
> Hosted by:

[Video Link](https://drive.google.com/file/d/16s5NZXhQmTxdrA83Sw3XHohbfEDJBei2/view?usp=sharing)

Is there any solution?

**Comment by RobinLinus** [comment]
interesting bug. no idea how to fix it though

**Comment by r-40021** [comment]
I have the same issue.
The only thing we can do is send feedback to Microsoft.
![image](https://user-images.githubusercontent.com/75155258/221181037-c5db54ad-797f-4e5d-9673-ec1170018ac6.png)

**Comment by rmpasswd** [comment]
> @rmpasswd do you have a link?

https://feedback.smartscreen.microsoft.com/feedback.aspx

This is the link, no mention of snapdrop.net in the url :/
They probably using session cookies.
This is the full page:

![image](https://user-images.githubusercontent.com/35218856/230454355-582d2d25-3f0d-43e1-a819-d82dcd844152.png)

**Comment by ericlaw1979** [comment]
The SmartScreen team is investigating. The "Report a false positive" flow mentioned above is the right one.

**Comment by ericlaw1979** [comment]
The SmartScreen team removed the false positive and testing shows that this issue is now Fixed.

Sorry for the hassle. If you see this in the future, please feel free to tag me.
