### ISSUE TITLE
Snapdrop App does not allow unofficial URL

### ISSUE THREAD

**Issue by Boerny41** [RobinLinus/snapdrop#576]
Hi,
I want to host my own instance of snapdrop for privacy reasons but it seems like the app changed and doesn't allow unofficial URLs anymore.

Would it be possible to just display a warning when entering an unofficial URL but still allowing it?

**Comment by RobinLinus** [comment]
The official server is getting hammered with way too much traffic these days. Other instances have to host their own server now.
