### ISSUE TITLE
Server down 'onedoessnapdrop-server-alonfoqgzq.now.sh'

### ISSUE THREAD

**Issue by Mateus109** [RobinLinus/snapdrop#58]
General problem that Snapdrop's server is down?

Error:  **onedoessnapdrop-server-alonfoqgzq.now.sh**

**Comment by Henboy10** [comment]
Am having the same problem

**Comment by PaulSzymanski** [comment]
Resolved

**Comment by docmars** [comment]
Just a heads up: it appears to be down / "unknown" again. 🙁

**Comment by RobinLinus** [comment]
@docmars https://snapdrop.net/ works, doesn't it?

**Comment by docmars** [comment]
@RobinLinus Ah apologies, I was using the one hosted on Github Pages—Snapdrop.net seems to be working nicely, thanks!

**Comment by MarcioAguiarMonteiro** [comment]
onedoessnapdrop-server-alonfoqgzq.now.sh

**Comment by MarcioAguiarMonteiro** [comment]
NÃO ESTOU CONSEGUINDO RESOLVER

**Comment by MarcioAguiarMonteiro** [comment]
https://onedoes.github.io/snapdrop/

**Comment by MarcioAguiarMonteiro** [comment]
https://snapdrop.net/




Não foi possível conectar

Ocorreu um erro durante uma conexão com snapdrop.net.

    Este site pode estar temporariamente fora do ar ou sobrecarregado. Tente de novo em alguns instantes.
    Se você não conseguir carregar nenhuma página, verifique a conexão de rede do computador.
    Se a rede ou o computador estiver protegido por um firewall ou proxy, verifique se o Firefox está autorizado a acessar a web.
