### ISSUE TITLE
Cannot save received file on iOS

### ISSUE THREAD

**Issue by frol** [RobinLinus/snapdrop#59]
iOS -> Computer (Linux, Firefox) works fine, but the other way around (* -> iOS) has an issue with the blob file, it feels like Safari does not support blob protocol:

![b803526b-8de7-4e4a-bb90-7a1c03886edf](https://user-images.githubusercontent.com/304265/45620255-eda0fc00-ba84-11e8-9137-dae71e5cb2e7.png)

iPhone SE, iOS 12.0

I think this may help: https://stackoverflow.com/questions/24485077/how-to-open-blob-url-on-chrome-ios/24531108#24531108

P.S. I have initially posted this in a closed issue #48, but decided to extract it into a separate issue.

**Comment by frol** [comment]
The issue remains the same. Please, consider reopening this issue.

**Comment by HenryTheX** [comment]
doesn't work on any of my i devices with iOS 12 exactly the same blob error
