### ISSUE TITLE
is the project still alive ?

### ISSUE THREAD

**Issue by dentonqlulu** [RobinLinus/snapdrop#595]
For a month now, no transfer can be done. Is the project dead?

**Comment by Troughy** [comment]
The snapdrop.net website doesn't really work for me either, but you can just use Docker to self-host it, so you can still keep using it.

**Comment by brunodeangelis** [comment]
Yesterday the website wasn't working, but now it seems to be :)

**Comment by RobinLinus** [comment]
should be up again
