### ISSUE TITLE
What browser?

### ISSUE THREAD

**Issue by SteveRMann** [RobinLinus/snapdrop#599]
Which browser on the PC works with snapdrop.net?  It works great when it opens on the PC, but it's rare that the website will open.  I've tried Edgs, Firefox, Opera and Chrome- nothing works.

**Comment by SteveRMann** [comment]
Thanks for pointing this out for me.

**Comment by rafaelrandom** [comment]
The "https://snapdrop.net/" instance never works for me, so I use "https://pairdrop.net/".
