### ISSUE TITLE
Transfer between iOS and desktop FireFox is broken

### ISSUE THREAD

**Issue by frol** [RobinLinus/snapdrop#60]
![screenshot from 2018-09-23 09-29-17](https://user-images.githubusercontent.com/304265/45924867-46ecad80-bf13-11e8-8cb1-12b80de22c20.png)

* iOS 12.0
* FireFox 62.0 (Arch Linux, x64)

As a side-note, the transfer works fine for iOS <-> desktop Google Chrome and desktop FireFox <-> desktop Google Chrome, and it used to work fine before the release of Snapdrop version 2.

**Comment by HenryTheX** [comment]
iOS 12 default safari doesnt work.
When receiving file it pop up a new tab and showing resource blob error

**Comment by RobinLinus** [comment]
Should be fixed with #61

**Comment by frol** [comment]
While the #61 is, indeed, resolved, this issue, specifically related to Firefox, is not. Though, it seems that the nature of the issue has changed. Now, it floods the inspector console with tons of `DOMException: "Cannot create offer in state have-local-offer"` and the whole browser (Firefox 62.0.3 Linux x64) goes completely unresponsive.
