### ISSUE TITLE
Is there a documented API for Snapdrop?

### ISSUE THREAD

**Issue by hwittenborn** [RobinLinus/snapdrop#602]
I'm wanting to start writing a GTK client for Snapdrop, but I'm lost on how I should connect the client to a Snapdrop server. I know that Snapdrop uses WebRTC, but is there any documentation on what messages should be coming between the client and server?

**Comment by RobinLinus** [comment]
The snapdrop server cannot serve third-party clients because that caused too much traffic

**Comment by hwittenborn** [comment]
@RobinLinus I'm doing this all on a third-party instance (see https://github.com/rhino-linux/drop). I just saw that there were some [third-party SnapDrop apps](https://github.com/RobinLinus/snapdrop/blob/master/docs/faq.md#third-party-apps), and I was hoping to mimic what they were doing from my client.

**Comment by hwittenborn** [comment]
Sounds good, I'll give that a look. Thanks a ton! :)
