### ISSUE TITLE
https://snapdrop.net/ down atm?

### ISSUE THREAD

**Issue by mxmilkiib** [RobinLinus/snapdrop#603]
Hi, just a note that the site is down atm!

I tried archive.org but I can't click on anything to get past the first page http://web.archive.org/web/20200729163235/https://snapdrop.net/ maybe some JS wasn't cached there?

**Comment by hwittenborn** [comment]
I'm noticing the same thing on my end. It's a project I'm working with (this message isn't affiliated with the project though, just me), but I've thrown up a SnapDrop instance at https://drop.rhinolinux.org if it'd be of interest until this instance goes back up.

**Comment by RobinLinus** [comment]
server is up again
