### ISSUE TITLE
Progressive app?

### ISSUE THREAD

**Issue by clragon** [RobinLinus/snapdrop#65]
Could snapdrop.net support the chrome function to be converted into an app on Android? 
That would be awesome. 
the fork on onedoes.github.io has that functionality.

**Comment by RobinLinus** [comment]
Thanks for your feedback!
Should be fixed...

**Comment by clragon** [comment]
Huh, interesting... I justed tested it and it didn't seem to work...

**Comment by RobinLinus** [comment]
Interesting... I just tested on Android 5.1 with Chrome 70 and it worked well. 

Can you give me more details on your setup please?

**Comment by clragon** [comment]
I'm on Android 8.0.0 with Chrome 69 but don't mind me, it works for me too now. Maybe I was just too soon and the website wasn't updated yet or ... I don't even know.
