### ISSUE TITLE
possible enhancement Rename computer

### ISSUE THREAD

**Issue by rekom** [RobinLinus/snapdrop#69]
Thank you for this great service:
would it be possible to rename the computer opening a snapdrop tab? 
If several computer use the same os and browser your are rapidly lost.

thanks

**Comment by winuxue** [comment]
same issue than #94

**Comment by 2br-2b** [comment]
I think it would be better if we assigned each computer a random name or ID when they connected to Snapdrop. We could also allow users to enter their own IDs, but then that could potentially lead to duplicates. This could be abused if a malicious actor were to assign their computer the same name as another recipient in an attempt to trick the users.

**Comment by PaulSzymanski** [comment]
This was resolved by https://github.com/RobinLinus/snapdrop/pull/91

**Comment by aaryanporwal** [comment]
Why can't we just show their IP?
