### ISSUE TITLE
Feature Request: Search app in Spotlight IOS

### ISSUE THREAD

**Issue by llgcode** [RobinLinus/snapdrop#71]
Hi,
In IOS when Snapdrop is installed in IOS, it could be great if we can search the app with keyword like "local" "file" "sharing" in spotligh. Don't know if it's a feature or something that you can do from your side.

regards

**Comment by RobinLinus** [comment]
Simply "add to home screen" and you are be able to search snapdrop in spotlight.

here's a how to:  https://www.lesson.ly/wp-content/uploads/2015/03/output_HLc06l.gif
