### ISSUE TITLE
local developement not working, help me please

### ISSUE THREAD

**Issue by gjimenezl** [RobinLinus/snapdrop#72]
Hello Robin, let me introduce myself my name is German Jimenez I live in Mexico / BCS. I have a laptop with Ubuntu 18.04 Desktop. Browsing and looking for an application like yours, I decided to try to install it since there is a small section that says: Local Development plus instructions and I comment the following:
1.- git clone git@github.com: RobinLinus / snapdrop.git
This first instruction, I could not execute it because I'm honest I did not know how on your GitHub / RobinLinus / Snapdrop page there is a section that says: Clone or Download and from here download the compressed file, extract it and leave it inside from the Downloads folder with the name snapdrop.
I opened a terminal session.
2.- npm install,
This command executes it but I had to install the following so that it could execute it:
apt get install npm
apt get install node
3.-node index.js
This command told me that a service was implemented, I show you how it is:
gjimenez @ Cabos: ~ / Downloads $ cd snapdrop
gjimenez @ Cabos: ~ / Downloads / snapdrop $ cd server
gjimenez @ Cabos: ~ / Downloads / snapdrop / server $ npm install
npm WARN snapdrop@1.0.0 No description
npm WARN snapdrop@1.0.0 No repository field.

audited 112 packages in 0.705s
found 0 vulnerabilities

gjimenez @ Cabos: ~ / Downloads / snapdrop / server $ node index.js
Snapdrop is running on port 3000
-------------------------------------------------- --------------------------------------------
In a second terminal session execute the following:

gjimenez @ Cabos: ~ $ cd Downloads
gjimenez @ Cabos: ~ / Downloads $ cd snapdrop
gjimenez @ Cabos: ~ / Downloads / snapdrop $ cd client
gjimenez @ Cabos: ~ / Downloads / snapdrop / client $ python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...

5000/5000
Character limit: 5000
Then on my laptop I opened the firefox and wrote: http: // localhost: 8000
-------------------------------------------------- ----------------------------------------------
On my IOS cellphone, I opened Safari and wrote: http://192.168.1.70:8000
-------------------------------------------------- ---------------------------------------------
On my celphone with safari, the web page appears with the following texts:
Open Snapdrop on other devices to send files.
and a legend that appears and disappears and says the following:
Connection lost. Retry in 5 second.
-------------------------------------------------- ---------------------------------------------
On my laptop it also indicates the same message:

Open Snapdrop on other devices to send files.

I have opened ports 3000 and 8000 for tcp and udp in the ubuntu 18.04 firewall.
And the server that runs on my laptop with the command:
gjimenez @ Cabos: ~ / Downloads / snapdrop / client $ python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
The following activity log appears:
127.0.0.1 - - [08 / Jan / 2019 23:49:34] "GET / HTTP / 1.1" 200 -
127.0.0.1 - - [08 / Jan / 2019 23:49:34] "GET /styles.css HTTP / 1.1" 200 -
127.0.0.1 - - [08 / Jan / 2019 23:49:34] "GET /scripts/network.js HTTP / 1.1" 200 -
127.0.0.1 - - [08 / Jan / 2019 23:49:34] "GET /scripts/ui.js HTTP / 1.1" 200 -
127.0.0.1 - - [08 / Jan / 2019 23:49:34] "GET /sounds/blop.mp3 HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:41] code 404, message File not found
192.168.1.66 - - [08 / Jan / 2019 23:49:41] "GET / server / webrtc HTTP / 1.1" 404 -
192.168.1.66 - - [08 / Jan / 2019 23:49:42] "GET / HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:42] "GET /styles.css HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:42] "GET /scripts/network.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:42] "GET /scripts/ui.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:43] code 404, message File not found
192.168.1.66 - - [08 / Jan / 2019 23:49:43] "GET / server / webrtc HTTP / 1.1" 404 -
192.168.1.66 - - [08 / Jan / 2019 23:49:43] "GET /sounds/blop.mp3 HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:43] "GET / HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:43] "GET /styles.css HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:43] "GET /scripts/network.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:43] "GET /scripts/ui.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:43] code 404, message File not found
192.168.1.66 - - [08 / Jan / 2019 23:49:43] "GET / server / webrtc HTTP / 1.1" 404 -
192.168.1.66 - - [08 / Jan / 2019 23:49:43] "GET /sounds/blop.mp3 HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET / HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET /styles.css HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET /scripts/network.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET /scripts/ui.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] code 404, message File not found
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET / server / webrtc HTTP / 1.1" 404 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET /sounds/blop.mp3 HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET / HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET /styles.css HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET /scripts/network.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET /scripts/ui.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] code 404, message File not found
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET / server / webrtc HTTP / 1.1" 404 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET /sounds/blop.mp3 HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:44] "GET / HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET /styles.css HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET /scripts/network.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET /scripts/ui.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] code 404, message File not found
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET / server / webrtc HTTP / 1.1" 404 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET /sounds/blop.mp3 HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET / HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET /styles.css HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET /scripts/network.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET /scripts/ui.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] code 404, message File not found
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET / server / webrtc HTTP / 1.1" 404 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET /sounds/blop.mp3 HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET / HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET /scripts/network.js HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET /styles.css HTTP / 1.1" 200 -
192.168.1.66 - - [08 / Jan / 2019 23:49:45] "GET /scripts/ui.js HTTP / 1.1" 200 -
------------------------------------------------------------------------------------------------
Finally I will appreciate if you can help me clarify what I am doing wrong. I really can offer to put a grain of sand to buy you a cup of coffee.

**Comment by bluenevus** [comment]
same issue here.  Help greatly appreciated
