### ISSUE TITLE
Home screen icon is very small

### ISSUE THREAD

**Issue by TitanNano** [RobinLinus/snapdrop#76]
After adding Snapdrop to my home screen, the icon is very small. 
![screenshot_20190217-144226](https://user-images.githubusercontent.com/4500858/52913916-d6c83500-32c2-11e9-957e-209f753c8593.png)

Firefox 67.0a

**Comment by RobinLinus** [comment]
Thank you for reporting this glitch! It should be fixed [with this commit].(https://github.com/RobinLinus/snapdrop/commit/16b64a98ccb1cec0528e238dfb2b2d151ead320c) 
Can you confirm please (after delete and reinstall) ?

**Comment by TitanNano** [comment]
Yes, looks better now! 👍 
![Screenshot_20190313-093030](https://user-images.githubusercontent.com/4500858/54264324-1ce78000-4573-11e9-9c54-d53b2ff3c00a.png)
