### ISSUE TITLE
yg.gl shortcut domain is down

### ISSUE THREAD

**Issue by marcsances** [RobinLinus/snapdrop#79]
Since a week or two, I can't use yg.gl shortcut to access the service. snapdrop.net works fine.

**Comment by wcomnisky** [comment]
Google turned off the URL shortner service.

**Comment by marcsances** [comment]
That's not related, .gl is a ccTLD for Greenland. yg.gl is not a Google shortened url, goo.gl is the Google shortening service which indeed is going down, but even if it was related, the shortened URLs are still available.

**Comment by wcomnisky** [comment]
You're right! I didn't realise it wasn't Goo.gl's URL.

And I also cannot access it too.

**Comment by idchlife** [comment]
Maybe it needs fund replenish? Domain is very handy, maybe we can help fund it or something?

**Comment by marcsances** [comment]
Whois says it (expired?) on March 18th and deadline for renewal is April 17th?

`Domain Name: yg.gl
Domain ID: 37215-GL
WHOIS Server: whois.nic.gl
Updated Date: 2019-03-18T12:03:10.818Z
Creation Date: 2015-12-31T09:22:49.264Z
Registry Expiry Date: 2016-12-31T09:22:49.332Z
Domain Status: pendingDelete https://icann.org/epp#pendingDelete
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: serverHold https://icann.org/epp#serverHold
Registrar: InterNetworX Ltd. & Co. KG
Redemption Expiry Date: 2019-04-17T12:03:10.818Z
Registrant ID: 37214-GL
Registrant Name: Redacted | EU Registrar
Registrant Street: Redacted | EU Registrar
Registrant City: Redacted | EU Registrar
Registrant Postal Code: Redacted | EU Registrar
Registrant Country: DE
Registrant Phone: Redacted | EU Registrar
Registrant Email: Redacted | EU Registrar
Admin ID: 37214-GL
Admin Name: Redacted | EU Registrar
Admin Street: Redacted | EU Registrar
Admin City: Redacted | EU Registrar
Admin Postal Code: Redacted | EU Registrar
Admin Country: DE
Admin Phone: Redacted | EU Registrar
Admin Email: Redacted | EU Registrar
Name Server: ns.inwx.de
Name Server: ns2.inwx.de
Name Server: ns3.inwx.eu
Name Server: ns4.inwx.com
Name Server: ns5.inwx.net
DNSSEC: unsigned
>>> Last update of WHOIS database: 2019-04-06T09:00:10.102Z <<<`

**Comment by idchlife** [comment]
@marcsances what does pending delete mean? Is it going to be deleted forever?

**Comment by marcsances** [comment]
ICANN is very clear about that: https://icann.org/epp#pendingDelete

The domain wil get deleted from the registry starting April 17th. Once that happens, it will be open for registration again.

**Comment by benblb** [comment]
yg.gl now goes to a spammy ad page. Snapdrop.net still showing it's an active shortcut.

**Comment by marceljay** [comment]
Not only spammy, but prompts downloads, probably containing malware or virusses.

**Comment by RobinLinus** [comment]
To fix this, please empty your browser cache. There's a new version deployed which doesn't reference yg.gl anymore.

**Comment by marcsances** [comment]
Yup, no mentions to the shortcut domain anymore.
