### ISSUE TITLE
Allow transfers to nearby on mobile data

### ISSUE THREAD

**Issue by mellodoot** [RobinLinus/snapdrop#80]
Not 100% sure how easy this would be to execute, but being able to transfer files to people nearby over mobile data would be a very useful feature. Would make snapdrop a go-to for any quick transfers for sure.

**Comment by idchlife** [comment]
I did not look into source code, but I suspect that there is IP check and user-agent, so basically only devices in the same network.

**Comment by Neikon** [comment]
Maybe with a QR system, it could pair both device

**Comment by PaulSzymanski** [comment]
Handled in #144
