### ISSUE TITLE
Apply a licence

### ISSUE THREAD

**Issue by floSoX** [RobinLinus/snapdrop#81]
Hello,

Thank you for this great App!
Please, could you apply a free/libre and open-source software licence to your code?
Like GPLv3 (https://www.gnu.org/licenses/quick-guide-gplv3.html)?

Help by GitHub : https://help.github.com/en/articles/adding-a-license-to-a-repository

Thank you in advance.

Regards,

**Comment by RobinLinus** [comment]
Thanks for the suggestion! 
Closed with #87
