### ISSUE TITLE
Have option to not prompt for each file

### ISSUE THREAD

**Issue by MatthewSteeples** [RobinLinus/snapdrop#82]
An enhancement to this would be to allow a device to send multiple files, and for the recipient to not have to accept each file individually as they're received.

Could be implemented as a tickbox that says something along the lines of "don't ask for future transfers from this device"

**Comment by NicolaGenesin** [comment]
@RobinLinus would you be interested in this?

I've implemented it on a fork https://github.com/NicolaGenesin/snapdrop/commit/7329e17620f31d805795cbd3d698b87dc48dadc9 , but I could make a more robust implementation and add a modal to let the user choose.

**Comment by dartrax** [comment]
This sounds great! Is this hosted somewhere and available for a test? Or even better, can it be integrated, @RobinLinus ?

**Comment by mendel3** [comment]
This would be an incredible feature

**Comment by RobinLinus** [comment]
Resolved with #104
