### ISSUE TITLE
Doesn't work with iOS on my PC

### ISSUE THREAD

**Issue by PopCorne** [RobinLinus/snapdrop#83]
Yesterday it works but today, I cannot transfer file between my phone and my desktop... the two devices are not connected, even though they are visible in the interface, that means the loading bar is only working on the phone (or the computer) but not on the output device. I tried to refresh the two pages, but it does nothing... can someone fix that?
![6983C2DA-ECE2-4B83-B313-85042A629317](https://user-images.githubusercontent.com/31096910/57023278-d983c680-6c31-11e9-82d8-39d21c17ca75.jpg)

**Comment by r33zA** [comment]
Having the same issue also.

**Comment by r33zA** [comment]
Mac to iOS and vise versa is fine, Windows to iOS and vise versa is a No go. However turning off the private network firewall in Windows it then works fine.

**Comment by asyba** [comment]
same issue iOS to Windows doesn't work, but iOS to Ubuntu it works.

**Comment by asyba** [comment]
> Mac to iOS and vise versa is fine, Windows to iOS and vise versa is a No go. However turning off the private network firewall in Windows it then works fine. You look to be on Linux, so not sure.

Do you know if there is a way to allow in the firewall but just for this website? to not disable the firewall globally

**Comment by morgannewman** [comment]
@RobinLinus Any insight into what about this app might possibly be causing the Windows firewall to prevent the transfer?

**Comment by klango** [comment]
I carried out a couple of tests using different Browsers. I used mobiles and a raspberry Pi running Raspbian. It seems to be related to the Browser itself instead system.
Here are the results: 

1. iPhone X Safari + Raspbian Firefox = works
2. iPhone X Safari + Raspbian Chromium =  mostly works. sometimes stuck transferring- (no popup receive file) 
3. Android Firefox 68.0 + Raspbian Firefox = doesnt
4. Android Firefox 68.0 + Raspbian Chromium = mostly works. sometimes stuck transferring- (no popup receive file) 
5. Android Chrome + Raspbian Chromium and Firefox   = works
6. Android Opera + Raspbian Chromium and Firefox = works

**Comment by otwieracz** [comment]
I have even more interesting case. Two devices:

1) iPhone X, browser does not matter
2) Windows 10, browser does not matter

In LAN A, no matter which browser is used, transfer does not start. In the same network, exchanging iPhone for Android works in any setup.
However, in LAN B, with the same devices - everything works.

Only difference betweel LAN A and B is network setup.
A) Ubiquiti Edgerouter X + TP-Link WD4300 with OpenWRT as Access Point
B) Some older TP-Link Wi-Fi router

@RobinLinus - could you please provide some details about differences in network requirements between Android and iOS? Because this seems to be problematic intersection on my network.

**Comment by edm00se** [comment]
I tried today and had trouble with Chrome, on Windows 10. Firefox on Windows was good. Both interacted with mobile Safari on iOS 12.4.1. I included a couple screen shots of my js console below to help.

| Browser   | OS               | Send   | Receive  | Notes                                    |
|------------|--------------|--------|---------|-----------------------------------|
| Chrome   | Win10          | ❌ [2] | ❌ [1] | Sent to/from iOS 12.4.1 Safari   |
| Firefox     | Win10         | ✔       |  ✔     | Sent to/from iOS 12.4.1 Safari   |
| Safari       | iOS 12.4.1   | ✔       | ✔      | Rec'd from FF/Win                     |

## JS console screen shots, in Chrome, of send/receive attempt:

<details><summary>
  [1] receive from iOS
  </summary><p>

*formatted* **heading** with [a](link)
![image](https://user-images.githubusercontent.com/622118/63949986-d2828e80-ca40-11e9-9961-73035f876b5f.png)

</p></details>

<details><summary>
  [2] send to iOS
  </summary><p>

![image](https://user-images.githubusercontent.com/622118/63949947-c39bdc00-ca40-11e9-87de-09ef5485af2a.png)

</p></details>

**Comment by otwieracz** [comment]
Please try disabling IPv6 - by unchecking it in adapter features in Windows I was able to get it working (probably hosts were trying to reach each other via IPv6, which is inoperative in my network)

-- 
sg

**Comment by edm00se** [comment]
My network, and both devices involved in my testing, have full IPv6 support. That said, disabling IPv6 for my PC's wireless adapter didn't appear to change the outcome; didn't work, looked to be the same error message in the js console.

**Comment by klango** [comment]
> My network, and both devices involved in my testing, have full IPv6 support. That said, disabling IPv6 for my PC's wireless adapter didn't change the outcome; didn't work, looked to be the same error message in the js console. Also, since it worked w/ IPv6 on Win10 w/ FF, I doubt it's Windows handling IPv6 that's the culprit, but rather more how Chrome on Win is handling things.
> 
> Update: Chrome on macOS does quite well, including anecdotally speaking, a faster experience.

So whats the status now, it just doesn't work using when using Chrome on Windows?

**Comment by edm00se** [comment]
@klango Coming back at this, I just did a couple tests with my iPhone 11 Pro running iOS 13.3 with mobile Safari at its corresponding version and was able to successfully send to and receive from a Windows 10 instance of Chrome (79.0.3945.117, latest stable). So this appears to be working for me as of today.

**Comment by klango** [comment]
@edm00se thats what I was going to say, just ran tests with that specific config (79.0) and seems to be working.

**Comment by RobinLinus** [comment]
Thanks for reporting! I'll close the issue then.
