### ISSUE TITLE
I wrote a cross-platform desktop app for Snapdrop

### ISSUE THREAD

**Issue by infin1tyy** [RobinLinus/snapdrop#84]
https://github.com/infin1tyy/snapdrop-desktop

Basically, it loads up the https://snapdrop.net website from within the electron app :) Just seems a bit more convenient than having to do it through your browser all the time (even though this is a browser, haha!)

I also wrote a React Native app for this named Snapdrop X (named after Telegram X) however it's not complete yet. At the moment I'm struggling to build for iOS, however, I have a working android build (thanks @dakyskye for testing!). You can download it here: https://uploadir.com/u/0zip9zyl

**Comment by mischnic** [comment]
With a recent Chrome, you can simply install it as a Desktop PWA. Same goes for Android

**Comment by infin1tyy** [comment]
Not everyone uses Chrome you know. I certainly don't.

**Comment by dakyskye** [comment]
> Not everyone uses Chrome you know. I certainly don't.

Right ! Firefox for the win.

**Comment by asyba** [comment]
in Windows is not working with PWA.

**Comment by nkoehring** [comment]
I'd like to see a CLI application :computer:

**Comment by RobinLinus** [comment]
Hey that's cool! 
I added a link to your app in the description.

**Comment by sneko** [comment]
@alextwothousand does it unlock speed limitation since "native"?

(I mean, from internet I'm able to reach 20MB/s but with Chrome it's 4-5x times slower. I guess that's due to native Chrome settings for websites...)
