### ISSUE TITLE
Blank icon on Android

### ISSUE THREAD

**Issue by lucius346346** [RobinLinus/snapdrop#97]
When I try to add Snapdrop to home screen I get blank icon.

Chrome
Android 9 Pie
MIUI

**Comment by winuxue** [comment]
Same here.
Maybe the icon is white whitout border over the white rectangle that MIUI adds to all icons

**Comment by Jnss98b** [comment]
It's because the icon doesn't have any shadow or border so it blends in with the background added by certain launchers to all app icons. The solution is simple, @RobinLinus just needs to add drop shadow to the current icon

**Comment by lucius346346** [comment]
Wouldn't it make more sense to make icon blue?

**Comment by RJCAM** [comment]
I think the problem is solved, because when I add it to my homescreen the icon shows blue.

**Comment by Jnss98b** [comment]
Yep same

**Comment by PaulSzymanski** [comment]
Working for me as well. Feel free to create a new issue if the problem still persists for someone.
