### ISSUE TITLE
Return to 426 Upgrade Required after running the server

### ISSUE THREAD

**Issue by 0x2a94b5** [RobinLinus/snapdrop#98]
```
$ git clone https://github.com/RobinLinus/snapdrop.git
$ cd snapdrop/server
$ npmi && node index.js
Snapdrop is running on port 3000
```
According to the nginx/default.conf configuration, visit http://ip/server, nginx does not report an error, but keeps prompting 426 Upgrade Required.

**Comment by Nover2** [comment]
Do you know how to solve it now?

**Comment by RJCAM** [comment]
Same here...when run "node index.js" it shows on the browser a blank screen with "Upgrade Required"

**Comment by PaulSzymanski** [comment]
The server is not serving the HTTP protocol. You are not supposed to visit `http://ip/server` in the browser. It is a websocket server and will only respond to that protocol.
If you try to start up snapdrop on your local machine for developing [try using docker-compose as described in the readme](https://github.com/RobinLinus/snapdrop#local-development).

**Comment by wyudong** [comment]
I got 426 error too and the reason is casued by incorrect nginx config. For future reference make sure you have these in nginx config:

```
location /server {
        proxy_pass http://node:3000;
        proxy_connect_timeout 300;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-for $remote_addr;
    }
```
